import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from 'esbuild';
import * as Core from '../../app/src/core/index.ts';
import { ANIM_JS } from '../../app/src/core/anim.ts';
import {
  PAGE_PACKAGE_FORMAT_V1, PORTABLE_PACKAGE_LIMITS_V1, SITE_PACKAGE_FORMAT_V1
} from '../../app/src/package/types.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const dist = join(here, 'dist');
const editorSource = join(root, 'index.html');
const editor = readFileSync(editorSource, 'utf8');

if (!editor.includes('window.PC_WORDPRESS') || !editor.includes('createWordPressHostAdapter')) {
  throw new Error('The Pagecraft build does not expose the WordPress host adapter.');
}

const unwrap = source => source.replace(/^<script>\n?/, '').replace(/<\/script>\s*$/, '').trim();
const runtimeSource = [
  Core.SLIDE_JS,
  Core.CODE_JS,
  Core.TABS_JS,
  Core.NAV_JS,
  Core.FACADE_JS,
  Core.LB_JS,
  `<script>\n${ANIM_JS}\n</script>`
].map(unwrap).join('\n\n');
const runtime = transformSync(runtimeSource, {
  loader: 'js',
  minify: true,
  target: 'es2017',
  legalComments: 'none'
}).code.trim();

mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'editor.html'), editor.replace(
  '<title>Pagecraft Builder</title>',
  '<title>Pagecraft for WordPress</title>'
));
writeFileSync(
  join(dist, 'runtime.js'),
  '/*! GENERATED by @pagecraft/editor. BP Animate licence is bundled by the consuming product. */\n'
    + runtime + '\n'
);
writeFileSync(join(dist, 'contract.json'), JSON.stringify({
  format: 'pagecraft.editor-contract.v1',
  editorVersion: '0.2.0',
  schemaVersion: Core.SCHEMA,
  rendererVersion: `pagecraft-core-${Core.SCHEMA}`,
  packages: {
    site: SITE_PACKAGE_FORMAT_V1,
    page: PAGE_PACKAGE_FORMAT_V1,
    limits: PORTABLE_PACKAGE_LIMITS_V1
  }
}, null, 2) + '\n');

console.log(`@pagecraft/editor artifacts written to ${dist}`);
