import * as C from '../../../../app/src/core/index.ts';
import type { Node, Doc } from '../../../../app/src/core/types.ts';
type S=Record<string,string>;
const n=(type:string,props:any={},d:S={},children:Node[]=[],m:S={})=>C.N(type,props,{d,t:{},m},children);
const text=(copy:string,size='20px',level='p',d:S={},m:S={})=>n('heading',{text:copy,level,ts:''},{'font-family':'inherit','font-size':size,'font-weight':'400','line-height':'1.3',margin:'0',...d},[],m);
const box=(kids:Node[],d:S={},m:S={})=>n('box',{layout:'block'},d,kids,m);
const img=(id:string,height='400px',m:S={})=>n('image',{src:`../assets/${id}.png`,alt:id==='terrace'?'Demonstration coastal holiday-home terrace overlooking the sea':'Demonstration cottage living room with blue shutters',lazy:0},{display:'block',width:'100%',height,'object-fit':'cover','border-radius':'0'},[],{height:'300px',...m});
const link=(copy:string,to='#homes',d:S={})=>n('button',{text:copy,link:to,ts:'',variant:'outline'},{'font-size':'16px','font-family':'inherit','font-weight':'500','background-color':'#173f65',color:'#fff','border-radius':'0','border-width':'0',padding:'16px 24px','min-height':'48px',...d});
const section=(kids:Node[],d:S={},m:S={})=>n('section',{}, {padding:'72px 48px',...d},kids,{padding:'40px 20px',...m});
const row=(kids:Node[],columns='1fr 1fr',d:S={},m:S={})=>box(kids,{display:'grid','grid-template-columns':columns,gap:'48px',...d},{'grid-template-columns':'1fr',gap:'24px',...m});
const intro=(title:string,copy:string)=>box([text(title,'44px','h2',{'letter-spacing':'-.03em'}, {'font-size':'32px'}),text(copy,'18px','p',{'margin-top':'16px','max-width':'48ch'})]);
function normalize(tree:Node[]){for(const x of tree){for(const bp of ['d','t','m'] as const){const out:S={};for(const [k,v]of Object.entries(x.css[bp])){if(k==='padding'||k==='margin'){const a=String(v).split(/\s+/);['top','right','bottom','left'].forEach((side,i)=>out[k+'-'+side]=[a[0],a[1]||a[0],a[2]||a[0],a[3]||a[1]||a[0]][i]);}else out[k]=String(v);}x.css[bp]=out;}normalize(x.children);}}
export function buildDirection(direction:'coastline'|'guestbook'|'collection'):Doc{
 C.seed();const colors=C.defaultTokens();colors.colors=[{id:'bg',name:'Chalk',value:'#faf9f4'},{id:'ink',name:'Sea ink',value:'#173f65'},{id:'text',name:'Text',value:'#18384c'},{id:'brand',name:'Blue',value:'#173f65'},{id:'surface',name:'Sand',value:'#efeadb'},{id:'muted',name:'Secondary',value:'#51606a'},{id:'line',name:'Divider',value:'#c0c7c8'}];
 C.state.meta={...C.state.meta,name:'Salt House',maxWidth:'1400px',size:'18px',font:C.stackFor('DM Sans','s'),headFont:C.stackFor('DM Sans','s'),css:'',headHtml:'',baseUrl:'',blocks:[],components:[],collections:[],tokens:colors};
 const nav=n('nav',{aria:'Main navigation',items:[{label:'The homes',href:'#homes'},{label:'The coast',href:'#coast'},{label:'Plan your stay',href:'#plan'}]},{'font-size':'16px',color:'inherit','--nav-panel':'#faf9f4','--nav-gap':'32px'});
 C.state.header=[section([box([text('Salt House','28px','div',{'font-weight':'600','letter-spacing':'-.04em','white-space':'nowrap','flex-shrink':'0'}),nav],{display:'flex','justify-content':'space-between','align-items':'center',gap:'24px'})],{padding:'24px 48px',color:'#173f65'},{padding:'20px'})];
 const property=(id:string,title:string,facts:string)=>box([img(id,'360px'),text(title,'28px','h3',{'margin-top':'24px','letter-spacing':'-.02em'}),text(facts,'16px','p',{'margin-top':'8px'}),link('Explore this home','#plan',{'margin-top':'20px','background-color':'transparent',color:'#173f65',padding:'12px 0','text-decoration':'underline'})]);
 let trees:Node[];
 if(direction==='coastline'){
   trees=[section([text('SALT HOUSE','150px','h1',{'font-weight':'600','line-height':'.9','letter-spacing':'-.07em','text-align':'center'},{'font-size':'64px'}),text('A few good homes. A little closer to the sea.','22px','p',{'text-align':'center','margin-top':'24px'},{'font-size':'18px'}),box([link('Find your coast')],{'text-align':'center','margin-top':'24px'})],{padding:'28px 48px 40px'}),section([img('terrace','500px')],{padding:'0'},{padding:'0'}),section([intro('Your kind of coast.','Room for slow mornings, salt on your skin and everyone around the same table.'),row([property('cottage','Blue Shutter Cottage','4 guests · 2 bedrooms · Village edge'),property('terrace','Dune House','6 guests · 3 bedrooms · Open-air terrace')],'1fr 1fr',{'margin-top':'40px'})],{'background-color':'#efeadb'})];
 }else if(direction==='guestbook'){
   trees=[section([row([box([text('STAY A\nLITTLE\nLONGER.','100px','h1',{'font-weight':'500','line-height':'.95','letter-spacing':'-.065em'},{'font-size':'62px'}),text('Salt House is a small collection of homes for days that unfold at your own pace.','20px','p',{'max-width':'28ch','margin-top':'28px'}),link('Meet the homes','#homes',{'margin-top':'28px'})]),img('terrace','650px')],'0.9fr 1.25fr',{'align-items':'center',gap:'64px'})],{'background-color':'#eedda9',padding:'40px 48px 64px'}),section([row([img('cottage','480px'),box([text('01 / BLUE SHUTTER COTTAGE','14px','p',{'letter-spacing':'.06em'}),text('Leave the\nshutters open.','52px','h2',{'letter-spacing':'-.04em','margin-top':'24px'},{'font-size':'36px'}),text('A quiet village home with room for four. A living room for long afternoons and the coast just beyond the door.','18px','p',{'margin-top':'24px','max-width':'38ch'}),text('4 guests · 2 bedrooms · 1 bathroom','16px','p',{'margin-top':'24px'}),link('A closer look','#plan',{'margin-top':'24px'})])],'1.2fr 1fr',{'align-items':'center'})])];
 }else{
   C.state.header[0].css.d['background-color']='#173f65';C.state.header[0].css.d.color='#fff';nav.css.d['--nav-panel']='#173f65';
   trees=[section([row([text('Good places.\nGreat days.','72px','h1',{'font-weight':'500','letter-spacing':'-.055em','line-height':'1.02'},{'font-size':'48px'}),box([text('Find the home that fits your people, your pace and your plans.','22px','p',{'max-width':'30ch'}),link('Compare the homes','#homes',{'margin-top':'24px'})])],'1.2fr 1fr',{'align-items':'end'}),row([property('terrace','Dune House','6 guests · 3 bedrooms · Terrace'),property('cottage','Blue Shutter Cottage','4 guests · 2 bedrooms · Village')],'1fr 1fr',{'margin-top':'48px'})],{padding:'48px'}),section([row([text('Less planning.\nMore being here.','48px','h2',{'letter-spacing':'-.04em'},{'font-size':'34px'}),box([text('Every home, clearly explained.','24px','h3'),text('Sleeping arrangements, practical amenities and arrival details help you choose with confidence. Availability and final prices come directly from the booking provider.','18px','p',{'margin-top':'20px'}),link('How to plan your stay','#plan',{'margin-top':'24px'})])])],{'background-color':'#efeadb'})];
 }
 trees[direction==='coastline'?2:direction==='guestbook'?1:0].adv.htmlId='homes';trees.push(section([intro('A coast to make your own.','Morning swims, village lunches and an unhurried walk home. Find a favourite stretch of sand and a new reason to come back.')],{padding:'48px'}));trees.at(-1)!.adv.htmlId='coast';
 if(direction==='coastline')trees[1].props.width='full';
 C.state.footer=[section([text('Start with a place.','40px','h2',{'letter-spacing':'-.03em'},{'font-size':'32px'}),text('Choose a home, then check dates and final prices with its booking provider.','18px','p',{'margin-top':'20px','max-width':'48ch'}),text('Salt House · Fictional collection · AI-generated demonstration images','14px','p',{'margin-top':'40px'})],{'background-color':'#173f65',color:'#fff'})];C.state.footer[0].adv.htmlId='plan';
 C.state.pages=[{id:'home',slug:'index',name:'Home',title:'Salt House — '+direction,desc:'A fictional small vacation-rental collection.',tree:trees}];C.state.cur=0;normalize(C.state.header);normalize(C.state.footer);normalize(trees);return structuredClone(C.doc());
}
