import * as C from '../../../app/src/core/index.ts';
import type {Doc,Node,Page,ComponentDef} from '../../../app/src/core/types.ts';
type S=Record<string,string>;let serial=0;
const color=C.cvar;
const n=(name:string,type:string,props:Record<string,any>={},d:S={},children:Node[]=[],m:S={},t:S={}):Node=>{const node=C.N(type,props,{d,t,m},children);node.id=`salt-${name}-${++serial}`;return node;};
const text=(copy:string,role='body',level='p',d:S={},m:S={})=>n('text','heading',{text:copy,level,ts:role},{margin:'0',...d},[],m);
const box=(name:string,kids:Node[],d:S={},m:S={})=>n(name,'box',{layout:'block'},d,kids,m);
const section=(name:string,kids:Node[],d:S={},m:S={})=>n(name,'section',{}, {padding:'80px 48px',...d},kids,{padding:'44px 20px',...m},{padding:'56px 32px'});
const row=(name:string,kids:Node[],columns='1fr 1fr',d:S={})=>box(name,kids,{display:'grid','grid-template-columns':columns,gap:'48px',...d},{'grid-template-columns':'1fr',gap:'28px'});
const alts:Record<string,string>={bedroom:'Fictional Dune House bedroom with blue linen and coastal views',terrace:'Fictional Dune House terrace overlooking coastal dunes and the sea',cottage:'Fictional Blue Shutter Cottage living room with pale linen and blue shutters',exterior:'Fictional Blue Shutter Cottage exterior beside a coastal village lane'};
const img=(id:string,height='440px',mobile='300px')=>n(id,'image',{src:`asset:${id}`,alt:alts[id],w:'1536',h:'1024',lazy:0},{display:'block',width:'100%',height,'object-fit':'cover','border-radius':'0'},[],{height:mobile},{height:'380px'});
const link=(copy:string,to:string,plain=false,d:S={})=>n('action','button',{text:copy,link:to,ts:'btn',variant:'outline'},{'background-color':plain?'transparent':color('brand'),color:plain?color('ink'):'#fff','border-radius':'0','border-width':'0',padding:plain?'12px 0':'16px 24px','min-height':'48px',...(plain?{'text-decoration':'underline','text-underline-offset':'6px'}:{}),...d});
const intro=(title:string,copy:string)=>section('page-opening',[text(title,'display','h1'),text(copy,'lead','p',{'max-width':'48ch','margin-top':'24px'})],{padding:'40px 48px 64px'});
const page=(slug:string,name:string,tree:Node[]):Page=>({id:`salt-page-${slug}`,slug,name,title:`${name} — Salt House`,desc:'A fictional collection of coastal holiday homes. Demonstration property details and AI-generated imagery.',tree});
const anchor=(node:Node,id:string)=>{node.adv.htmlId=id;return node;};
const bind=(node:Node,prop:string,path:string)=>{node.bind={...(node.bind||{}),[prop]:{src:'prop',path}};return node;};
function propertyDefinition():ComponentDef{
 const image=bind(bind(img('cottage','370px'),'src','image'),'alt','alt');image.showIf={bind:{src:'prop',path:'image'},op:'set'};
 return {id:'salt-property',name:'Holiday home',node:box('property',[image,box('property-caption',[bind(text('Blue Shutter Cottage','subtitle','h2'),'text','title'),bind(text('4 guests · 2 bedrooms · Village edge','small','p',{'margin-top':'10px'}),'text','facts'),bind(text('An easy village base, with the sea beyond the shutters.','body','p',{'margin-top':'16px','max-width':'44ch'}),'text','description'),bind(link('Explore this home','blue-shutter-cottage.html',true,{'margin-top':'12px'}),'link','destination')],{'padding-top':'24px'})],{'min-width':'0'}),props:[{k:'title',label:'Home name',t:'text',def:'Blue Shutter Cottage'},{k:'facts',label:'Home facts',t:'text',def:'4 guests · 2 bedrooms · Village edge'},{k:'description',label:'Home description',t:'text',def:'An easy village base, with the sea beyond the shutters.'},{k:'image',label:'Home photograph',t:'img',def:'asset:cottage'},{k:'alt',label:'Photo description',t:'text',def:alts.cottage},{k:'destination',label:'Home page',t:'link',def:'blue-shutter-cottage.html'}]};
}
const property=(dune=false)=>{const x=box('home-instance',[]);x.use='salt-property';x.vals=dune?{title:'Dune House',facts:'6 guests · 3 bedrooms · Open-air terrace',description:'Space for a larger gathering, with mornings out on the terrace.',image:'asset:terrace',alt:alts.terrace,destination:'dune-house.html'}:{title:'Blue Shutter Cottage',facts:'4 guests · 2 bedrooms · Village edge',description:'An easy village base, with the sea beyond the shutters.',image:'asset:cottage',alt:alts.cottage,destination:'blue-shutter-cottage.html'};return x;};
const homes=()=>row('home-collection',[property(),property(true)]);
const note=()=>text('Fictional homes and example details. Images are AI-generated; no real rental availability is offered.','small','p',{'margin-top':'32px',color:color('muted'),'max-width':'75ch'});
const editorial=(title:string,copy:string)=>box('reading-group',[text(title,'title','h2'),text(copy,'body','p',{'margin-top':'20px','max-width':'48ch'})]);
function home():Page{
 const photograph=section('coastal-panorama',[img('terrace','500px','300px')],{padding:'0'},{padding:'0'});photograph.props.width='full';photograph.css.t.padding='0';
 return page('index','Home',[
 section('brand-opening',[text('SALT HOUSE','brandmark','h1',{'text-align':'center'}),text('A few good homes. A little closer to the sea.','lead','p',{'text-align':'center','margin-top':'24px'}),box('opening-action',[link('Find your coast','homes.html')],{'text-align':'center','margin-top':'24px'})],{padding:'28px 48px 40px'}),photograph,
 section('choose-home',[editorial('Your kind of coast.','Room for slow mornings, salt on your skin and everyone around the same table.'),box('homes-spacing',[homes()],{'margin-top':'40px'}),note()],{'background-color':color('surface')}),
 section('village-story',[row('village-and-copy',[img('exterior','510px','360px'),box('coast-reading',[text('Beyond the front door.','title','h2'),text('A walk through the village. Lunch in the shade. A last look at the water before heading home.','lead','p',{'margin-top':'24px','max-width':'32ch'}),link('Meet the coast','coast.html',true,{'margin-top':'24px'})])],'1.2fr 1fr',{'align-items':'center',gap:'72px'})])]);
}
function collection():Page{return page('homes','The Homes',[intro('Find your place.','Two different ways to stay by the sea. Start with the space your group needs.'),section('all-homes',[homes(),note()],{padding:'0 48px 72px'}),section('choosing',[row('choosing-guide',[editorial('The right fit,\nbefore the dates.','Choose a home by its rooms, setting and practical details.'),box('choosing-details',[text('More room outside','subtitle','h3'),text('Dune House pairs three example bedrooms with a broad terrace.','body','p',{'margin-top':'12px'}),text('A smaller village base','subtitle','h3',{'margin-top':'32px'}),text('Blue Shutter Cottage offers two example bedrooms and a sheltered living room.','body','p',{'margin-top':'12px'}),link('Planning a stay','plan-your-stay.html',true,{'margin-top':'20px'})])])],{'background-color':color('surface')})]);}
function detail(dune:boolean):Page{
 const name=dune?'Dune House':'Blue Shutter Cottage';const id=dune?'terrace':'cottage';
 const fact=(heading:string,copy:string)=>box('home-fact',[text(heading,'small','h3',{color:color('muted')}),text(copy,'subtitle','p',{'margin-top':'10px'})],{'padding-top':'20px','border-top':'1px solid '+color('line')});
 const gallery=n('property-gallery','gallery',{items:(dune?['bedroom']:['exterior']).map(x=>({src:`asset:${x}`,alt:alts[x],w:1536,h:1024,caption:x==='exterior'?'The village setting':'A place to settle in'})),ratio:'3 / 2',fit:'cover',lightbox:1,lazy:0,captions:1},{'--g-cols':'1','--g-gap':'24px','--g-radius':'0'},[],{'--g-cols':'1'});
 const hero=img(id,'620px','370px');if(!dune)hero.css.m['object-position']='80% center';
 return page(dune?'dune-house':'blue-shutter-cottage',name,[
 intro(name,dune?'Long lunches. Open horizons. Room for everyone.':'Blue shutters, pale linen and a slower village rhythm.'),section('property-scene',[hero],{padding:'0 48px 48px'}),
 section('property-details',[row('property-story',[box('home-narrative',[text(dune?'Life, out on the terrace.':'A home between village and sea.','title','h2'),text(dune?'The outdoor table is the center of this example home: somewhere to gather after a swim, spread out lunch or stay with a book. Inside, three bedrooms give a family or small group their own space.':'A shaded living room opens toward the coast. This example cottage is a smaller base for a couple or family, with two bedrooms and village life nearby.','lead','p',{'margin-top':'24px'}),note()]),box('stay-summary',[text('At a glance','subtitle','h2'),fact('Guests',dune?'Up to 6':'Up to 4'),fact('Bedrooms',dune?'3 bedrooms':'2 bedrooms'),fact('Bathrooms',dune?'2 bathrooms':'1 bathroom'),link('Ask about this home','plan-your-stay.html#inquiry',false,{'margin-top':'28px'}),text('Demonstration only. Booking is not connected.','small','p',{'margin-top':'16px',color:color('muted')})])],'1.4fr 1fr',{gap:'80px'})]),
 section('practical-details',[row('amenities',[editorial('The everyday details.','Useful information makes choosing easier.'),box('amenities-list',[text(dune?'Three example bedrooms: two doubles and one twin.':'Two example bedrooms: one double and one twin.','body'),text('Example amenities: equipped kitchen, dining space, Wi-Fi and washing machine.','body','p',{'margin-top':'24px'}),text(dune?'Outdoor terrace with dining table. Confirm steps, access and suitability with the host before booking.':'Village setting with a living room for afternoons indoors. Confirm steps, parking and access with the host before booking.','body','p',{'margin-top':'24px'})])])],{'background-color':color('surface')}),
 section('photo-details',[text('A closer look.','title','h2'),box('gallery-spacing',[gallery],{'margin-top':'32px'})]),
 section('next-home',[row('other-home',[editorial('A different kind of stay.',dune?'Prefer a smaller village base? Meet Blue Shutter Cottage.':'Need an extra bedroom and more outdoor space? Meet Dune House.'),link(dune?'Explore Blue Shutter Cottage':'Explore Dune House',dune?'blue-shutter-cottage.html':'dune-house.html',true)],'1.5fr 1fr',{'align-items':'center'})],{'background-color':color('surface')})]);
}
function coast():Page{return page('coast','The Coast',[intro('A little further\nfrom the everyday.','A fictional coastal setting, made for time outdoors and unhurried days.'),section('coast-picture',[img('terrace','560px','340px')],{padding:'0 48px 64px'}),section('coast-day',[row('day-itinerary',[text('Leave the day open.','title','h2'),box('day-sequence',[editorial('Morning by the water.','A walk along the shore, then breakfast back at the house.'),box('midday',[editorial('The village at lunchtime.','Find a shaded table and let lunch take its time.')],{'margin-top':'40px'}),box('evening',[editorial('One more hour outside.','Return to the terrace as the light softens.')],{'margin-top':'40px'})])],'1fr 1.5fr')],{'background-color':color('surface')}),section('local-guide',[row('village-guide',[img('exterior','460px','340px'),box('travel-advice',[text('Know the place\nbefore you arrive.','title','h2'),text('Ask your host for verified directions, beach access, transport options and seasonal opening hours. Check local swimming conditions on the day.','body','p',{'margin-top':'24px'}),text('This setting is fictional. No real route, restaurant or distance is implied.','small','p',{'margin-top':'24px',color:color('muted')}),link('Plan your stay','plan-your-stay.html',true,{'margin-top':'20px'})])],'1.1fr 1fr',{'align-items':'center'})])]);}
function plan():Page{
 const faq=n('stay-questions','accordion',{open:'none',single:0,marker:'plus',items:[{q:'How do I check dates and prices?',a:'This demonstration collection is not connected to a booking provider. A real host must supply a working booking link with current availability, full prices and terms.'},{q:'What should I confirm before booking?',a:'Check the total cost, cancellation terms, sleeping arrangements, access, parking and any rules that matter to your group.'},{q:'Can I send an inquiry here?',a:'The form below is disabled until a receiving service is connected. No message is delivered while it is unconfigured.'},{q:'Are these real properties?',a:'No. Salt House is a fictional collection with example details and AI-generated imagery.'}]},{'--ac-q-size':'22px','--ac-a-size':'18px','--ac-q-color':color('ink'),'--ac-a-color':color('text'),'--ac-pad':'24px','--ac-line':color('line')},[],{'--ac-q-size':'19px','--ac-a-size':'17px'});
 const form=n('stay-inquiry','form',{mode:'external',action:'',aria:'Stay inquiry',submit:'Send inquiry',fields:[{label:'Name',name:'name',type:'text',required:1,half:1},{label:'Email',name:'email',type:'email',required:1,half:1},{label:'Home, dates and guests',name:'stay',type:'textarea',required:1}]},{'font-size':'18px','--f-radius':'0','--f-bg':color('bg'),'--f-btn-bg':color('brand'),'--f-btn-fg':'#fff'});
 return page('plan-your-stay','Plan Your Stay',[intro('Start with your people.','Choose the space you need, then confirm the dates and details with the host.'),section('planning-questions',[row('questions-and-intro',[editorial('Before you make plans.','Straight answers to the practical questions.'),faq],'1fr 1.6fr')],{'background-color':color('surface')}),anchor(section('inquiry',[row('inquiry-columns',[box('inquiry-context',[text('Tell us what\nyou have in mind.','title','h2'),text('Include your preferred home, approximate dates and group size. Leave payment details and sensitive documents out of your message.','body','p',{'margin-top':'24px'}),text('This demo form is not connected. No inquiry can be sent until a receiving service is configured.','small','p',{'margin-top':'24px',color:color('muted')})]),form],'1fr 1.5fr')]),'inquiry')]);
}
function normalize(nodes:Node[]){for(const x of nodes){for(const bp of ['d','t','m'] as const){const out:S={};for(const [k,v]of Object.entries(x.css[bp])){if(k==='padding'||k==='margin'){const a=String(v).split(/\s+/);['top','right','bottom','left'].forEach((side,i)=>out[k+'-'+side]=[a[0],a[1]||a[0],a[2]||a[0],a[3]||a[1]||a[0]][i]);}else out[k]=String(v);}x.css[bp]=out;}normalize(x.children);}}
export function buildTemplateDocument():Doc{
 C.seed();serial=0;const tokens=C.defaultTokens();tokens.colors=Object.entries({bg:'#faf9f4',ink:'#173f65',text:'#18384c',brand:'#173f65',surface:'#efeadb',muted:'#51606a',line:'#c0c7c8'}).map(([id,value])=>({id,name:({bg:'Chalk',ink:'Sea ink',text:'Body text',brand:'Sea blue',surface:'Sand',muted:'Secondary text',line:'Divider'} as Record<string,string>)[id],value}));
 const sizes:Record<string,string[]>={display:['76px','60px','46px'],title:['44px','38px','32px'],subtitle:['28px','26px','26px'],lead:['22px','21px','19px'],body:['18px','18px','17px'],small:['16px','16px','14px'],btn:['16px','16px','16px']};
 for(const t of tokens.text)if(sizes[t.id])t.css={d:{'font-family':'inherit','font-size':sizes[t.id][0],'font-weight':'400','line-height':['display','title','subtitle'].includes(t.id)?'1.08':'1.5','letter-spacing':['display','title','subtitle'].includes(t.id)?'-.035em':'0'},t:{'font-size':sizes[t.id][1]},m:{'font-size':sizes[t.id][2]}};
 tokens.text.push({id:'brandmark',name:'Hero brand',tag:'h1',css:{d:{'font-family':'inherit','font-size':'150px','font-weight':'600','line-height':'.9','letter-spacing':'-.07em'},t:{'font-size':'110px'},m:{'font-size':'64px'}}});
 C.state.meta={...C.state.meta,name:'Salt House',lang:'en',maxWidth:'1400px',size:'18px',font:C.stackFor('DM Sans','s'),headFont:C.stackFor('DM Sans','s'),css:'',headHtml:'',baseUrl:'',ogImage:'asset:terrace',favicon:'',blocks:[],components:[propertyDefinition()],collections:[],selfHostFonts:0,tokens};
 const brand=text('Salt House','subtitle','div',{'font-weight':'600','white-space':'nowrap','flex-shrink':'0'});brand.props.link='index.html';
 C.state.header=[section('header',[box('header-row',[brand,n('navigation','nav',{aria:'Main navigation',items:[{label:'The homes',href:'homes.html'},{label:'The coast',href:'coast.html'},{label:'Plan your stay',href:'plan-your-stay.html'}]},{'font-size':'16px',color:color('ink'),'--nav-panel':color('bg'),'--nav-gap':'32px'})],{display:'flex','justify-content':'space-between','align-items':'center',gap:'24px'})],{padding:'24px 48px'},{padding:'20px'})];
 C.state.footer=[section('footer',[row('closing',[text('See you by the sea.','title','h2',{color:'#fff'}),box('closing-action',[link('Find your home','homes.html',false,{'background-color':color('bg'),color:color('ink')}),link('Plan your stay','plan-your-stay.html',true,{color:'#fff','margin-left':'24px'})])],'1fr 1fr',{'align-items':'center'}),box('colophon',[text('SALT HOUSE','subtitle','div',{color:'#fff','font-weight':'600'}),text('Fictional collection · AI-generated demonstration images','small','p',{color:'#fff'})],{display:'flex','justify-content':'space-between',gap:'24px','margin-top':'64px','padding-top':'24px','border-top':'1px solid #708ba1'},{'flex-direction':'column','margin-top':'40px'})],{'background-color':color('brand')})];
 C.state.pages=[home(),collection(),detail(true),detail(false),coast(),plan()];C.state.cur=0;normalize(C.state.header);normalize(C.state.footer);C.state.pages.forEach(p=>normalize(p.tree));C.state.meta.components?.forEach(c=>normalize([c.node]));return structuredClone(C.doc());
}
