import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from 'esbuild';
import * as Core from '../../app/src/core/index.ts';
import { ANIM_JS } from '../../app/src/core/anim.ts';

const here = dirname(fileURLToPath(import.meta.url));
const output = process.argv[2]
  ? resolve(process.argv[2])
  : resolve(here, '../pagecraft-builder/assets/pagecraft-runtime.js');
const unwrap = source => source
  .replace(/^<script>\n?/, '')
  .replace(/<\/script>\s*$/, '')
  .trim();

const source = [
  Core.SLIDE_JS,
  Core.CODE_JS,
  Core.TABS_JS,
  Core.NAV_JS,
  Core.FACADE_JS,
  Core.LB_JS,
  `<script>\n${ANIM_JS}\n</script>`
].map(unwrap).join('\n\n');
const compiled = transformSync(source, {
  loader: 'js', minify: true, target: 'es2017', legalComments: 'none'
}).code.trim();
const runtime = '/*! GENERATED by wordpress/tools/build-runtime.mjs. Includes BP Animate 1.2.2; MIT licence in assets/BP-ANIMATE-LICENSE.txt. */\n'
  + compiled + '\n';

mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, runtime);
