import * as Core from '../../../app/src/core/index.ts';
import type { Doc, Node, Page, ComponentDef } from '../../../app/src/core/types.ts';
const N=Core.N,C=Core.cvar;
let serial=0;
type Style=Record<string,string>;
const named=(n:Node,name:string)=>{n.id=`cg2-${name}-${++serial}`;return n;};
const box=(name:string,kids:Node[],d:Style={},m:Style={})=>named(N('box',{layout:'block'},{d,t:{},m},kids),name);
const h=(copy:string,level='h2',ts=level==='h1'?'display':'title',d:Style={},m:Style={})=>named(N('heading',{text:copy,level,ts},{d:{margin:'0',...d},t:{},m}),'heading');
const p=(copy:string,ts='body',d:Style={})=>named(N('heading',{text:copy,level:'p',ts},{d:{margin:'0',...d},t:{},m:{}}),'paragraph');
const image=(id:string,alt:string,height='480px',mobile='320px')=>named(N('image',{src:`asset:${id}`,alt,w:'1536',h:'1024',lazy:0},{d:{display:'block',width:'100%',height,'object-fit':'cover','border-radius':'0'},t:{height:'400px'},m:{height:mobile,...(id==='studio-table'?{'object-position':'80% top','height':'230px'}:{})}}),id);
const section=(name:string,kids:Node[],d:Style={},m:Style={})=>named(N('section',{}, {d:{padding:'72px 48px',...d},t:{padding:'48px 32px'},m:{padding:'40px 20px',...m}},kids),name);
const grid=(name:string,kids:Node[],columns='1fr 1fr',d:Style={})=>box(name,kids,{display:'grid','grid-template-columns':columns,gap:'32px',...d},{'grid-template-columns':'1fr',gap:'32px'});
const link=(copy:string,href:string,d:Style={})=>named(N('button',{text:copy,link:href,ts:'btn',variant:'outline'},{d:{'background-color':'transparent',color:C('ink'),'border-width':'0','border-radius':'0',padding:'12px 0','min-height':'44px','text-decoration':'underline','text-underline-offset':'6px','align-self':'start',...d},t:{},m:{}}),'link');
const anchor=(n:Node,id:string)=>{n.adv.htmlId=id;return n;};
const reading=(name:string,title:string,copy:string)=>box(name,[h(title),p(copy,'body',{'margin-top':'16px','max-width':'60ch'})]);
const page=(slug:string,name:string,tree:Node[]):Page=>({id:slug==='index'?'page-home':`page-${slug}`,slug,name,title:`${name} — Common Ground`,desc:'A fictional architecture practice. Architecture and adaptive reuse studies, with native editable Pagecraft content.',tree});
const intro=(title:string,copy:string)=>section('page-intro',[h(title,'h1'),p(copy,'lead',{'max-width':'55ch','margin-top':'24px'})],{padding:'40px 48px 64px'});
const courtyard='Fictional pale-brick courtyard house with oak-framed openings';
const room='Fictional reading room beneath retained oak trusses';
const header=()=>section('header',[box('header-row',[
 h('Common Ground','div','wordmark',{'white-space':'nowrap','flex-shrink':'0'}),
 named(N('nav',{collapse:'900',aria:'Main navigation',items:[{label:'Projects',href:'projects.html'},{label:'Practice',href:'about.html'},{label:'Services',href:'services.html'},{label:'Contact',href:'contact.html'}]},{d:{color:C('ink'),'font-size':'16px','--nav-gap':'32px','--nav-panel':C('paper'),'--nav-hover':C('brand')},t:{},m:{}}),'navigation')
],{display:'flex','justify-content':'space-between','align-items':'center',gap:'24px'})],{padding:'24px 48px'},{padding:'20px'});
function bind(n:Node,prop:string,path:string){n.bind={...(n.bind||{}),[prop]:{src:'prop',path}};return n;}
function projectDefinition():ComponentDef{
 const media=bind(bind(image('courtyard-interior','Fictional oak-framed room looking into the brick courtyard','400px','300px'),'src','image'),'alt','alt');media.showIf={bind:{src:'prop',path:'image'},op:'set'};
 return {id:'project-plate',name:'Project plate',node:box('project-plate',[media,box('plate-caption',[
 bind(h('Courtyard house','h2','title',{'font-size':'32px'}),'text','title'),bind(p('Residential study','small',{'margin-top':'8px',color:C('muted')}),'text','category'),bind(p('A home gathered around a garden.','body',{'margin-top':'16px','max-width':'52ch'}),'text','description'),bind(bind(link('Explore the study','project-detail.html'),'text','action'),'link','link')
 ],{'padding-top':'24px'})],{'min-width':'0'}),props:[{k:'title',label:'Project title',t:'text',def:'Courtyard house'},{k:'category',label:'Project type',t:'text',def:'Residential study'},{k:'description',label:'Project description',t:'text',def:'A home gathered around a garden.'},{k:'image',label:'Project image',t:'img',def:'asset:courtyard-interior'},{k:'alt',label:'Image description',t:'text',def:courtyard},{k:'link',label:'Project destination',t:'link',def:'project-detail.html'},{k:'action',label:'Project action',t:'text',def:'Explore the study'}]};
}
const project=(values:Record<string,string>={})=>{const n=box('project-instance',[]);n.use='project-plate';n.vals={title:'Courtyard house',category:'Residential / Design study',description:'An outdoor room at the center of the home. Brick gives it enclosure; oak openings connect the rooms to the garden.',image:'asset:courtyard-interior',alt:'Fictional oak-framed room looking into the brick courtyard',link:'project-detail.html',action:'Explore the study',...values};return n;};
const roomProject=()=>project({title:'Workshop reading room',category:'Adaptive reuse / Design study',description:'A long table beneath an existing roof. A shared room shaped by what the workshop already offers: structure, light and a garden edge.',image:'asset:reading-room',alt:room,link:'projects.html#reading-room',action:'Read the reuse study'});
const close=()=>section('close',[
 h('Let’s make room\nfor what comes next.','h2','closing',{color:C('paper')}),p('A home to change. A building to reuse. A place to share.','body',{'margin-top':'24px',color:C('paper')}),link('Start a conversation','contact.html',{color:C('paper'),'margin-top':'16px'}),box('colophon',[p('Common Ground','small',{color:C('paper')}),p('Fictional practice · AI-generated design studies','small',{color:C('paper')}),link('About the practice','about.html',{color:C('paper'),padding:'0'})],{display:'flex','justify-content':'space-between','align-items':'center',gap:'24px','margin-top':'64px','padding-top':'24px','border-top':'1px solid #a77e72'},{'flex-direction':'column','align-items':'start',gap:'12px','margin-top':'40px'})
],{'background-color':C('brand')});
function home():Page{return page('index','Home',[
 section('image-opening',[image('courtyard-house',courtyard,'510px','340px')],{padding:'0 48px'},{padding:'0 20px'}),
 section('opening-title',[h('Architecture, close to life.','h1'),p('Homes, shared spaces and a thoughtful second life for existing buildings.','lead',{'margin-top':'20px','max-width':'58ch'}),link('Discover the project studies','projects.html')],{padding:'32px 48px 72px'}),
 section('selected-projects',[h('Two places. Two possibilities.'),p('Studies in making more of what is already there.','body',{'margin-top':'16px','margin-bottom':'32px'}),grid('paired-projects',[project(),roomProject()],'1fr 1fr',{'margin-top':'32px'})],{'background-color':C('surface')}),
 section('practice',[grid('practice-material',[image('studio-table','Fictional architecture worktable with courtyard model and material samples','460px','300px'),box('practice-copy',[h('Look closely.\nBuild thoughtfully.'),p('The starting point is a place and the people who will use it. How the light moves. What a wall holds. Where the day comes together.','lead',{'margin-top':'24px'}),p('These observations shape the two demonstration studies: a house around an open court, and a workshop given a shared purpose.','body',{'margin-top':'24px'}),link('Inside the practice','about.html')],{'align-self':'center','max-width':'520px'})],'1.1fr 1fr',{gap:'64px'})])
]);}
function projects():Page{return page('projects','Projects',[
 intro('Places, reconsidered.','Two fictional design studies. Each starts with a simple spatial question, then follows it through light, material and everyday use.'),
 section('project-plates',[grid('project-collection',[project(),roomProject()])],{padding:'0 48px 72px'}),
 anchor(section('reading-room',[image('reading-room',room,'560px','340px'),box('reading-narrative',[h('A room for the neighborhood.'),p('Workshop reading room','small',{'margin-top':'12px',color:C('muted')}),p('Keep the brick shell and the rhythm of the roof. Place a long shared table where the daylight falls. Open the garden edge so a former workshop becomes a place to read, meet and stay.','lead',{'margin-top':'24px','max-width':'58ch'}),link('Discuss an existing building','contact.html')],{'max-width':'780px','padding-top':'32px'})],{'background-color':C('surface')}),'reading-room')
]);}
function detail():Page{return page('project-detail','Courtyard house',[
 intro('An open room.\nA gathered home.','Courtyard house explores how a sheltered outdoor space can organize the rooms around it.'),
 section('detail-scene',[image('courtyard-house',courtyard,'640px','390px')],{padding:'0 48px 40px'}),
 section('detail-reading',[grid('project-context',[box('project-facts',[h('Courtyard house','h2','subtitle'),p('Residential design study','small',{'margin-top':'12px'}),p('Pale brick · Oak · Gravel garden','small',{'margin-top':'8px'}),p('Fictional project, not a completed commission.','small',{'margin-top':'24px',color:C('muted')})]),box('project-story',[h('The garden is the center.'),p('Rather than putting the garden at the end of the plan, this study brings it inward. Rooms face the court; their daily routines meet at an open patch of sky.','lead',{'margin-top':'24px'}),p('The brick edge provides enclosure. Timber-framed openings keep the threshold between indoors and outdoors legible. A tree, a table and a place to sit give the court a purpose beyond its view.','body',{'margin-top':'24px'})])],'1fr 2fr')]),
 section('detail-material',[grid('material-and-method',[image('studio-table','Fictional model and material studies on an architecture worktable','440px','300px'),reading('material-note','From a room to a material.','A small model and a limited material family help test the proposition. In this demonstration, brick defines the enclosure and timber marks the points of contact. The image is a fictional working scene, not technical documentation.')],'1.2fr 1fr',{'align-items':'center',gap:'64px'})],{'background-color':C('surface')})
]);}
function about():Page{return page('about','Practice',[
 intro('Attention to the ordinary.','Common Ground is a demonstration architecture practice concerned with the places that hold everyday life.'),
 section('studio',[image('studio-table','Fictional architecture studio model and material worktable','560px','340px')],{padding:'0 48px 64px'}),
 section('approach',[h('A practice of looking carefully.'),p('Before a drawing, there is a conversation. Before a material choice, there is a place to understand.','lead',{'max-width':'52ch','margin-top':'24px'}),grid('approach-sequence',[reading('listen','Listen.','Make the brief specific: the rooms you use, the routines that matter and the changes you need.'),reading('retain','Retain.','Look for useful fabric and existing character before deciding what needs to be replaced.'),reading('make-clear','Make clear.','Use drawings, models and plain language to explain choices and unresolved questions.')],'1fr 1fr 1fr',{'margin-top':'48px'})],{'background-color':C('surface')}),
 section('practice-disclosure',[p('This is a fictional practice, not a real professional service. No team, registration, awards or client experience is implied. Template owners should replace the demonstration narrative with verified practice information.','small',{'max-width':'80ch',color:C('muted')})])
]);}
function services():Page{
 const row=(title:string,copy:string,output:string)=>box('service-row',[h(title,'h2','title'),p(copy),p(output,'small',{color:C('muted')})],{display:'grid','grid-template-columns':'1fr 1.4fr 1fr',gap:'40px',padding:'32px 0'},{'grid-template-columns':'1fr',gap:'16px'});
 const rows=[row('Find the possibility.','Early feasibility explores the brief, the site and the constraints before a direction is fixed.','Example outputs: working brief, constraints and initial options.'),row('Shape the home.','Explore the relationship between rooms, daylight and outdoor space through an alteration or new residential study.','Example outputs: spatial proposal, material direction and next decisions.'),row('Give it another life.','Consider how an existing building can hold a different use while retaining what gives it value.','Example outputs: reuse strategy, outline layout and technical questions.')];
 rows.slice(1).forEach(n=>n.css.d['border-top']='1px solid '+C('line'));
 return page('services','Services',[intro('From a question\nto a clear direction.','A focused conversation can establish what your project needs, what is known and what should be explored next.'),section('service-scopes',rows,{'background-color':C('surface'),padding:'32px 48px'}),section('prepare',[grid('prepare-content',[image('studio-table','Fictional architecture model and material studies','400px','280px'),reading('first-meeting','Bring the place with you.','Photographs, an address, existing drawings if available, and a sense of timing and budget make a useful beginning. These are example service scopes; actual appointments, fees and responsibilities must be agreed for each project.')],'1fr 1fr',{'align-items':'center',gap:'64px'})])]);
}
function contact():Page{return page('contact','Contact',[
 intro('Tell us about\nyour place.','What is there now, and what could it become? Start with the location, the building and the change you have in mind.'),
 section('contact-form',[grid('contact-columns',[named(N('form',{mode:'external',action:'',aria:'Project inquiry',submit:'Send inquiry',fields:[{label:'Name',name:'name',type:'text',required:1,half:1},{label:'Email',name:'email',type:'email',required:1,half:1},{label:'About the project',name:'project',type:'textarea',required:1}]},{d:{'font-size':'18px','--f-bg':C('paper'),'--f-radius':'0','--f-btn-bg':C('brand'),'--f-btn-fg':C('paper')},t:{},m:{}}),'inquiry-form'),box('inquiry-context',[h('A useful first message.','h2','subtitle'),p('Include the location, current use, and the main change you would like to make. Avoid sensitive documents until you have agreed how they will be handled.','body',{'margin-top':'20px'}),p('This demonstration form needs a receiving service. The template owner must configure and test delivery before accepting inquiries.','small',{'margin-top':'32px',color:C('muted')})])],'1.6fr 1fr',{gap:'64px'})],{padding:'0 48px 72px'})
]);}
export function buildTemplateDocument():Doc{
 Core.seed();serial=0;const tokens=Core.defaultTokens();
 const palette:Record<string,string>={bg:'#f8f5ef',paper:'#f8f5ef',ink:'#462822',text:'#382e29',brand:'#6d342a',surface:'#e9e0d3',muted:'#6e5a4e',line:'#c8b6a3'};
 tokens.colors=Object.entries(palette).map(([id,value])=>({id,name:({bg:'Page background',paper:'Paper',ink:'Heading ink',text:'Body text',brand:'Brick',surface:'Linen',muted:'Secondary text',line:'Divider'} as Record<string,string>)[id],value}));
 const sizes:Record<string,[string,string,string]>={display:['80px','58px','44px'],title:['40px','36px','32px'],subtitle:['26px','24px','24px'],lead:['22px','21px','20px'],body:['18px','18px','17px'],small:['14px','14px','14px'],btn:['16px','16px','16px']};
 for(const t of tokens.text)if(sizes[t.id])t.css={d:{...(['display','title','subtitle'].includes(t.id)?{}:{'font-family':'inherit'}),'font-size':sizes[t.id][0],'font-weight':'400','line-height':['display','title','subtitle'].includes(t.id)?'1.08':'1.55','letter-spacing':['display','title'].includes(t.id)?'-.025em':'0'},t:{'font-size':sizes[t.id][1]},m:{'font-size':sizes[t.id][2]}};
 tokens.text.push({id:'wordmark',name:'Practice name',tag:'div',css:{d:{'font-family':Core.stackFor('Instrument Serif','f'),'font-size':'32px','font-weight':'400','line-height':'1.1','letter-spacing':'-.025em'},t:{},m:{'font-size':'26px'}}});
 tokens.text.push({id:'closing',name:'Closing title',tag:'h2',css:{d:{'font-size':'64px','font-weight':'400','line-height':'1.1'},t:{'font-size':'52px'},m:{'font-size':'40px'}}});
 Core.state.meta={...Core.state.meta,name:'Common Ground',maxWidth:'1344px',size:'18px',lang:'en',font:Core.stackFor('DM Sans','s'),headFont:Core.stackFor('Instrument Serif','f'),css:'',headHtml:'',baseUrl:'',ogImage:'asset:courtyard-house',favicon:'',blocks:[],components:[projectDefinition()],collections:[],selfHostFonts:0,tokens};
 Core.state.header=[header()];Core.state.header[0].children[0].children[0].props.link='index.html';Core.state.footer=[close()];Core.state.pages=[home(),projects(),detail(),about(),services(),contact()];Core.state.pages[1].tree[2].children.shift();Core.state.cur=0;
 // Native saves can canonicalize CSS key order. Expand spacing shorthands so
 // default longhands cannot regain precedence after an editor round trip.
 const normalize=(nodes:Node[])=>{for(const n of nodes){for(const bp of ['d','t','m'] as const){const out:Style={};for(const [key,value] of Object.entries(n.css[bp])){if(key==='padding'||key==='margin'){const a=String(value).trim().split(/\s+/);const v=[a[0],a[1]||a[0],a[2]||a[0],a[3]||a[1]||a[0]];['top','right','bottom','left'].forEach((side,i)=>out[`${key}-${side}`]=v[i]);}else out[key]=String(value);}n.css[bp]=out;}normalize(n.children);}};
 normalize(Core.state.header);normalize(Core.state.footer);for(const p of Core.state.pages)normalize(p.tree);for(const c of Core.state.meta.components||[])normalize([c.node]);
 return structuredClone(Core.doc());
}
