import * as C from '../../../app/src/core/index.ts';
import type {Doc,Node,Page,ComponentDef} from '../../../app/src/core/types.ts';
type S=Record<string,string>;let serial=0;const c=C.cvar;
const n=(name:string,type:string,props:Record<string,any>={},d:S={},children:Node[]=[],m:S={},t:S={}):Node=>{const x=C.N(type,props,{d,t,m},children);if(type==='image'&&!name.includes('logo')){x.st={hover:{d:{filter:'brightness(1.04)'},t:{},m:{}}};x.css.d.transition='filter 400ms ease';}x.id=`cove-${name}-${++serial}`;return x;};
const txt=(text:string,ts='body',level='p',d:S={})=>n('copy','heading',{text,ts,level},{margin:'0',...d});
const box=(name:string,kids:Node[],d:S={},m:S={},t:S={})=>n(name,'box',{layout:d.display==='grid'?'grid':d.display==='flex'?'flex':'block'},d,kids,m,t);
const sec=(name:string,kids:Node[],d:S={},m:S={})=>n(name,'section',{}, {padding:'80px 40px',...d},kids,{padding:'56px 20px',...m},{padding:'48px 32px'});
const btn=(text:string,link:string,outline=false)=>n('action','button',{text,link,ts:'btn'},{'background-color':outline?'transparent':c('brand'),color:outline?c('ink'):'#fff','border-radius':'8px',padding:'15px 24px','min-height':'48px','border-width':outline?'1px':'0','border-style':'solid','border-color':c('line')});
const image=(id:string,h='460px',mh='280px')=>n(id,'image',{src:`asset:${id}`,alt:`Illustrative ${id==='hero'?'coastal villa with pool':id==='terrace'?'palm-shaded terrace':id==='dining'?'outdoor breakfast table':id==='coast'?'tropical bay':'ocean-view bedroom'}; generated demonstration image`,lazy:0},{display:'block',width:'100%',height:h,'object-fit':'cover','border-radius':'0'},[],{height:mh});
const anchor=(x:Node,id:string)=>{x.adv.htmlId=id;return x;};
const row=(name:string,kids:Node[],cols='1fr 1fr')=>box(name,kids,{display:'grid','grid-template-columns':cols,gap:'40px','align-items':'start'},{'grid-template-columns':'1fr',gap:'28px'});
const intro=(title:string,copy:string)=>box('intro',[txt(title,'title','h2'),txt(copy,'body','p',{'margin-top':'16px','max-width':'64ch'})]);
const homes=[{name:'Cove House',slug:'cove-house',asset:'hero',facts:'6 guests · 3 bedrooms · Pool terrace',desc:'Open doors, an open horizon, and room to gather around the table.'},{name:'Palm Terrace',slug:'palm-terrace',asset:'terrace',facts:'4 guests · 2 bedrooms · Outdoor dining',desc:'A shaded terrace for long lunches and unhurried afternoons.'},{name:'The Lookout',slug:'the-lookout',asset:'bedroom',facts:'2 guests · 1 bedroom · Ocean view',desc:'A smaller hideaway for waking slowly, with the sea in sight.'}];
const bind=(x:Node,key:string,path:string)=>{x.bind={...x.bind,[key]:{src:'prop',path}};return x;};
function propertyDefinition():ComponentDef{return {id:'cove-property',name:'Vacation home feature',node:box('property-shell',[bind(bind(image('hero','340px','240px'),'src','image'),'alt','alt'),box('property-copy',[bind(txt('Cove House','subtitle','h3'),'text','title'),bind(txt('Example home details','small','p',{'margin-top':'16px',color:c('muted')}),'text','facts'),bind(txt('A place by the sea.','body','p',{'margin-top':'24px'}),'text','description'),box('property-action',[bind(btn('View home','cove-house.html'),'link','destination')],{'margin-top':'28px'})],{padding:'40px',display:'flex','flex-direction':'column','justify-content':'center'},{padding:'24px'})],{display:'grid','grid-template-columns':'1.5fr 1fr','background-color':'#fff','border-radius':'10px',overflow:'hidden','min-width':'0'},{'grid-template-columns':'1fr'}),props:[{k:'title',label:'Home name',t:'text',def:'Cove House'},{k:'facts',label:'Home facts',t:'text',def:'Example property details'},{k:'description',label:'Description',t:'text',def:'A place by the sea.'},{k:'image',label:'Property photo',t:'img',def:'asset:hero'},{k:'alt',label:'Image description',t:'text',def:'Illustrative vacation home'},{k:'destination',label:'Property page',t:'link',def:'cove-house.html'}]};}
const property=(i:number)=>{const h=homes[i];const x=box('property-instance',[]);x.use='cove-property';x.vals={title:h.name,facts:h.facts,description:h.desc,image:`asset:${h.asset}`,alt:`Illustrative ${h.name}; generated demonstration photograph`,destination:h.slug+'.html'};return x;};
const slider=()=>n('properties','slider',{arrows:1,aria:'Vacation homes'},{'--sl-w':'92%','--sl-gap':'24px'},homes.map((_,i)=>property(i)),{'--sl-w':'92%','--sl-gap':'16px'});
function inquiry(home?:string,compact=false){const fields=[{label:'Arrival',name:'arrival',type:'date',required:1,half:1},{label:'Departure',name:'departure',type:'date',required:1,half:1},{label:'Guests',name:'guests',type:'select',opts:'1 guest,2 guests,3 guests,4 guests,5 guests,6 guests',half:1,required:1},{label:'Preferred home',name:'home',type:'select',opts:home||'Any home,Cove House,Palm Terrace,The Lookout',half:1,required:1},{label:'Name',name:'name',type:'text',half:1,required:1},{label:'Email',name:'email',type:'email',half:1,required:1}];const visibleFields=compact?fields.filter(f=>f.name!=='home'&&(!home||f.name!=='name')):fields;return n(home?'booking-inquiry':'hero-inquiry','form',{mode:'external',action:'',method:'post',aria:home?`Booking inquiry for ${home}`:'Plan your stay',submit:'Send inquiry',fields:visibleFields},{'font-size':'18px','--f-radius':'6px','--f-gap':'12px','--f-pad':'9px 12px','--f-bg':'#fff','--f-border':c('line'),'--f-text':c('ink'),'--f-label':c('ink'),'--f-btn-bg':c('brand'),'--f-btn-fg':'#fff'});}
function staySearch(){const form=inquiry(undefined,true);form.props.aria='Search stays';form.props.submit='Search stays';form.props.fields=(form.props.fields||[]).filter(f=>['arrival','departure','guests'].includes(f.name||''));form.css.d={...form.css.d,'align-items':'end','--f-layout':'grid','--f-columns':'repeat(4,minmax(0,1fr))','--f-button-align':'end'};form.css.t={'--f-columns':'repeat(2,minmax(0,1fr))'};form.css.m={'--f-columns':'1fr'};return form;}
const faq=()=>box('faq-list',[{q:'How do I book a stay?',a:'Choose a home and send your preferred dates to the host. Your reservation is confirmed only after you receive a booking confirmation.'},{q:'Where can I see the full price?',a:'Request a quote for your dates, including fees and taxes.'},{q:'What should I check before booking?',a:'Confirm sleeping arrangements, accessibility, cancellation terms, check-in times and house rules directly with your host.'}].map((item,i)=>box('faq-row',[n('question','accordion',{open:'none',single:1,marker:'plus',items:[item]},{'--ac-q-size':'20px','--ac-a-size':'17px','--ac-pad':'24px','--ac-line':'transparent','--ac-q-color':c('ink'),'--ac-a-color':c('text')})],i?{'border-top':'1px solid '+c('line')}:{})));
const page=(slug:string,name:string,tree:Node[]):Page=>({id:`cove-page-${slug}`,slug,name,title:`${name} — Cove & Key`,desc:'An illustrative coastal vacation-rental collection with booking inquiries.',tree});
function home():Page{
 const heroPhoto=image('hero','100%','100%');heroPhoto.css.d={...heroPhoto.css.d,position:'absolute',inset:'0','border-radius':'0','object-position':'center 58%'};heroPhoto.css.m={...heroPhoto.css.m,top:'200px',height:'220px'};
 const shade=box('hero-shade',[],{position:'absolute',inset:'0','background-image':'linear-gradient(180deg,rgba(7,36,52,.96) 0%,rgba(7,36,52,.8) 38%,rgba(7,36,52,0) 78%)'}, {display:'none'});
 const heading=txt('A little closer to the sea.','display','h1',{color:'#fff','text-align':'center','max-width':'1040px',margin:'0 auto'});
 const content=box('hero-content',[heading,txt('Find a coastal home. Tell us how you like to stay.','lead','p',{color:'#fff','text-align':'center',margin:'16px auto 0'})],{position:'relative','z-index':'1','max-width':'1280px',margin:'0 auto',padding:'76px 40px',width:'100%'},{padding:'24px 20px','background-color':c('ink'),height:'200px'});
 const stage=box('hero-stage',[heroPhoto,shade,content],{position:'relative',height:'560px',overflow:'hidden'},{height:'420px'});
 const hero=sec('hero',[stage],{padding:'0'},{padding:'0'});hero.props.width='full';hero.css.t={padding:'0'};
 const planner=box('wide-planner',[txt('Find your stay','subtitle','h2',{'font-size':'22px'}),box('planner-fields',[staySearch()],{'margin-top':'14px'})],{padding:'24px 32px','background-color':'#fff','border-radius':'12px',position:'relative',transform:'translateY(-98px)','margin-bottom':'-98px','z-index':'2'},{padding:'22px',transform:'translateY(-32px)','margin-bottom':'-32px'});
 const plannerSection=anchor(sec('hero-planner',[planner],{padding:'0 40px','background-color':c('surface')},{padding:'0 20px'}),'inquiry');plannerSection.css.t={padding:'0 32px'};
 const days=row('coastal-day',[box('day-photo',[image('dining','480px','300px')]),box('day-story',[txt('Make room for slower days.','title','h2'),txt('A late breakfast. A shaded terrace. One more swim before dinner. The best part of getting away is having time for all of it.','body','p',{'margin-top':'24px','max-width':'36ch'}),box('day-action',[btn('Explore the coast','the-coast.html')],{'margin-top':'28px'})],{display:'flex','flex-direction':'column','justify-content':'center',height:'100%',padding:'32px'},{padding:'12px 0'})],'1.25fr 1fr');
 const quote=(copy:string,homeName:string)=>box('guest-words',[n('guest-quote','quote',{text:copy,by:'',source:'',ts:'title'},{margin:'0 auto','max-width':'30ch','font-size':'34px','font-weight':'500','line-height':'1.3'},[],{'font-size':'26px'}),txt(homeName+' · Sample review','small','p',{'margin-top':'24px',color:c('muted'),'text-align':'center'})],{padding:'24px 72px','text-align':'center'},{padding:'24px 48px'});
 return page('index','Coastal vacation rentals',[
 hero,plannerSection,
 anchor(sec('homes',[box('inventory-heading',[n('inventory-title','heading',{text:'Find your kind of away.',ts:'title',level:'h2'},{margin:'0','font-size':'44px'},[],{'font-size':'30px'},{'font-size':'36px'}),txt('Three homes. Three ways to spend a little more time by the sea.','body','p',{'margin-top':'16px'})],{}, {'font-size':'inherit'}),box('property-slider',[slider()],{'margin-top':'28px'}),box('all-stays',[btn('Compare the homes','stays.html',true)],{'margin-top':'24px'})],{'background-color':c('surface'),padding:'48px 40px 72px'}),'stays'),
 sec('coastal-days',[days]),
 sec('guest-reviews',[box('review-layout',[box('review-title',[txt('The stays that stay with you.','title','h2',{'text-align':'center'}),txt('Sample guest stories from our demo collection.','small','p',{'margin-top':'16px',color:c('muted'),'text-align':'center'})],{'text-align':'center'}),n('review-slider','slider',{arrows:1,controlsPosition:'bottom',aria:'Illustrative guest reviews'},{'--sl-w':'100%','--sl-gap':'24px','margin-top':'32px'},[quote('Slow breakfasts outside became our favourite part of the day.','Cove House'),quote('We came for the view. We stayed on the terrace.','Palm Terrace'),quote('Coffee, an open window, and nothing on the schedule. Just what we needed.','The Lookout'),quote('Long lunches together, then one more swim before sunset.','Cove House')],{'--sl-w':'100%','--sl-gap':'24px'},{'--sl-w':'100%'})],{'max-width':'1000px',margin:'0 auto'})],{'background-color':c('surface')}),
 sec('before-arrival',[box('planning-layout',[image('terrace','560px','300px'),box('planning-content',[intro('A little planning. A lot to look forward to.','The practical details, before you pick your place.'),box('answers',[faq()],{'margin-top':'24px'})])],{display:'grid','grid-template-columns':'1fr 1fr',gap:'56px','align-items':'center'},{'grid-template-columns':'1fr',gap:'32px'})])
 ]);
}
function collection():Page{return page('stays','Find your stay',[sec('stays-opening',[txt('Find a home that feels like your holiday.','display','h1',{'max-width':'900px'}),txt('Find the space, setting and sleeping arrangements that suit your people.','lead','p',{'margin-top':'24px','max-width':'65ch'})]),sec('all-properties',[box('property-list',homes.map((_,i)=>property(i)),{display:'grid',gap:'36px'})],{padding:'0 40px 96px'}),sec('finding-your-fit',[intro('A few details make all the difference.','Consider your group size, outdoor space and access needs before choosing your stay.'),box('compare',[n('comparison','table',{head:1,body:'Home|Guests|Bedrooms|Setting\nCove House|6|3|Pool terrace\nPalm Terrace|4|2|Garden terrace\nThe Lookout|2|1|Ocean view',rules:'rows'},{'--tbl-size':'17px','--tbl-caption-size':'14px','--tbl-pad':'16px','--tbl-line':c('line')})],{'margin-top':'32px'}),box('help',[btn('Help me choose','contact.html#inquiry')],{'margin-top':'32px'})],{'background-color':c('surface')})]);}
function booking(i:number){const h=homes[i];return anchor(box('booking-widget',[txt('Make this your next stay.','subtitle','h2'),txt('Choose your dates and start planning your stay.','body','p',{'margin-top':'16px'}),box('booking-form',[inquiry(h.name,true)],{'margin-top':'24px'}),txt('Preview only. Reservations are not available yet.','small','p',{'margin-top':'20px',color:c('muted')})],{padding:'32px','background-color':c('surface'),'border-radius':'12px'},{padding:'24px'}),'booking');}
function detail(i:number):Page{const h=homes[i];const gallery=n('gallery','gallery',{items:[{src:`asset:${h.asset}`,alt:`Illustrative ${h.name}`,caption:h.name+''},{src:'asset:coast',alt:'Illustrative coastal setting',caption:'Around the coast'}],ratio:'3 / 2',fit:'cover',lightbox:1,lazy:0,captions:1},{'--g-cols':'2','--g-gap':'16px','--g-radius':'12px'},[],{'--g-cols':'1'});return page(h.slug,h.name,[sec('detail-heading',[btn('All stays','stays.html',true),txt(h.name,'display','h1',{'margin-top':'20px'}),txt(h.desc,'lead','p',{'margin-top':'20px'}),txt(h.facts+'','small','p',{'margin-top':'16px',color:c('muted')})],{padding:'32px 40px'}),sec('detail-gallery',[gallery],{padding:'0 40px 64px'}),sec('detail-and-booking',[row('details-booking',[box('details',[intro(i===0?'Room for everyone.':i===1?'Life moves outdoors.':'A view worth waking up to.',i===0?'Start with the terrace. A long table, places to sit and an open view create the setting for time together. Inside, three bedrooms give your group room to settle in.':i===1?'Palms frame a sheltered outdoor living space. Two bedrooms make it a place for a small group who would rather spend the afternoon outside.':'Open the doors and let the horizon into the room. This one-bedroom retreat keeps the essentials close, with a private place to read and rest.'),box('amenities',[txt('At home here','subtitle','h2'),box('amenity-facts',[
box('sleeping',[txt('Sleeping arrangements','body','h3',{'font-weight':'700'}),txt(i===0?'Two double bedrooms and one twin bedroom.':i===1?'One double bedroom and one twin bedroom.':'One double bedroom.','body','p',{'margin-top':'8px'})]),
box('outdoors',[txt('Outdoor living','body','h3',{'font-weight':'700'}),txt(i===0?'Pool terrace and outdoor dining.':i===1?'Shaded lounge and garden terrace.':'Private ocean-view balcony.','body','p',{'margin-top':'8px'})]),
box('essentials',[txt('Everyday essentials','body','h3',{'font-weight':'700'}),txt('Equipped kitchen · Dining area · Wi-Fi · Bed linen · Towels','body','p',{'margin-top':'8px'})])],{display:'grid',gap:'24px','margin-top':'24px'})],{'margin-top':'40px'}),box('policies',[txt('Before you confirm','subtitle','h2'),txt('Check the total price, cancellation policy, check-in and check-out times, accessibility and house rules with the host. ','body','p',{'margin-top':'16px'})],{'margin-top':'40px'})]),booking(i)],'1.15fr 1fr')],{padding:'32px 40px 96px'}),sec('nearby',[intro('The coast is part of the stay.','Take a look at the setting, then ask the host for real local recommendations.'),box('coast-link',[btn('Explore the coast','the-coast.html')],{'margin-top':'28px'})],{'background-color':c('surface')}),sec('another-stay',[intro('Another way to stay.','Explore a different space in the collection.'),box('related',[property((i+1)%3)],{'margin-top':'32px'})])]);}
function coast():Page{return page('the-coast','The coast',[sec('coast-heading',[txt('Leave a little room for the coast.','display','h1',{'max-width':'900px'}),txt('An imagined setting for days outside and evenings without a timetable.','lead','p',{'margin-top':'24px'})]),sec('coast-scene',[image('coast','540px','320px')],{padding:'0 40px 64px'}),sec('coast-guide',[intro('Build a day around what you love.','A morning near the water. A long lunch. An afternoon entirely your own.'),box('coast-choices',[row('coast-activities',[box('water',[txt('Find your stretch of water','subtitle','h2'),txt('Ask for the nearest beach, local access and current swimming conditions. A good local recommendation is better than a guessed distance.','body','p',{'margin-top':'16px'})]),box('food',[txt('Make lunch the plan','subtitle','h2'),txt('Bring something back to the terrace or ask your host for a favourite table nearby. Leave time to linger.','body','p',{'margin-top':'16px'})])])],{'margin-top':'40px'}),box('coast-action',[btn('Find a coastal home','stays.html')],{'margin-top':'32px'})]),sec('lunch-scene',[image('dining','440px','300px'),txt('Room for one more slow afternoon.','title','h2',{'margin-top':'32px'}),txt('Take the day as it comes.','small','p',{'margin-top':'16px',color:c('muted')})],{'background-color':c('surface')})]);}
function story():Page{return page('our-story','Our story',[sec('story-opening',[txt('Good stays begin with a sense of place.','display','h1',{'max-width':'900px'}),txt('A small collection of coastal homes, each with its own way of making you feel away. Come for the setting. Stay for the ordinary moments that feel different here.','lead','p',{'margin-top':'24px','max-width':'62ch'})]),sec('story-image',[image('dining','500px','300px')],{padding:'0 40px 64px'}),sec('story-principles',[intro('The details that make room for a good holiday.','A clear view of the home. Practical information before you commit. An easy way to ask the questions that matter.'),box('principles',[row('principles-row',[box('see',[txt('See the space','subtitle','h2'),txt('Photographs and room details help you imagine your days before you choose where to stay.','body','p',{'margin-top':'16px'})]),box('ask',[txt('Talk through your plans','subtitle','h2'),txt('An inquiry starts a conversation. Dates, access needs and the right sleeping arrangements belong in it.','body','p',{'margin-top':'16px'})])])],{'margin-top':'40px'}),box('story-actions',[btn('Explore the collection','stays.html'),btn('Get in touch','contact.html',true)],{display:'flex','flex-wrap':'wrap',gap:'16px','margin-top':'36px'})])]);}
function contact():Page{return page('contact','Plan your stay',[sec('contact-opening',[txt('Tell us what your holiday looks like.','display','h1',{'max-width':'1200px'}),txt('A home you like, a few dates, and the people coming with you. Start there.','lead','p',{'margin-top':'24px','max-width':'60ch'})]),anchor(sec('contact-form',[row('contact-layout',[box('contact-context',[txt('A little help choosing?','title','h2'),txt('Tell us who is coming and what matters to you. We can help you find the right space for your stay.','body','p',{'margin-top':'20px'}),box('contact-photo',[image('terrace','300px','240px')],{'margin-top':'28px'})]),box('contact-planner',[txt('Plan your stay','subtitle','h2'),box('contact-fields',[inquiry()],{'margin-top':'24px'})],{padding:'32px','background-color':c('surface'),'border-radius':'12px'},{padding:'24px'})])],{padding:'0 40px 80px'}),'inquiry'),sec('contact-faq',[intro('A few things before you send.','Dates, sleeping arrangements, and the details that matter to your group.'),box('contact-answers',[faq()],{'margin-top':'28px'})],{'background-color':c('surface')})]);}

function normalize(nodes:Node[]){for(const x of nodes){for(const bp of ['d','t','m'] as const){const out:S={};for(const[k,v]of Object.entries(x.css[bp])){if(k==='padding'||k==='margin'){const a=String(v).split(/\s+/);['top','right','bottom','left'].forEach((s,i)=>out[k+'-'+s]=[a[0],a[1]||a[0],a[2]||a[0],a[3]||a[1]||a[0]][i]);}else out[k]=String(v)}x.css[bp]=out;}normalize(x.children)}}
export function buildTemplateDocument():Doc{C.seed();serial=0;const tokens=C.defaultTokens();tokens.colors=Object.entries({bg:'#ffffff',ink:'#123344',text:'#284d60',brand:'#007da5',surface:'#eaf5f8',muted:'#526b78',line:'#bdcfd7'}).map(([id,value])=>({id,name:id,value}));const sizes:Record<string,string[]>={display:['60px','48px','34px'],title:['36px','30px','27px'],subtitle:['27px','24px','22px'],lead:['19px','18px','17px'],body:['18px','18px','17px'],small:['14px','14px','14px'],btn:['16px','16px','16px']};for(const t of tokens.text)if(sizes[t.id])t.css={d:{'font-family':'inherit','font-size':sizes[t.id][0],'font-weight':['display','title','subtitle'].includes(t.id)?'700':'400','line-height':['display','title','subtitle'].includes(t.id)?'1.15':'1.6','letter-spacing':['display','title','subtitle'].includes(t.id)?'-.03em':'0'},t:{'font-size':sizes[t.id][1]},m:{'font-size':sizes[t.id][2]}};C.state.meta={...C.state.meta,name:'Cove & Key',lang:'en',maxWidth:'1280px',size:'18px',font:C.stackFor('Manrope','s'),headFont:C.stackFor('Manrope','s'),css:'',headHtml:'',baseUrl:'',ogImage:'asset:hero',favicon:'asset:symbol',blocks:[],components:[propertyDefinition()],collections:[],selfHostFonts:0,tokens};
const logo=n('logo','image',{src:'asset:logo',alt:'Cove & Key',link:'index.html'},{width:'200px',height:'42px','object-fit':'contain'},[],{width:'172px',height:'40px'});
const headerAction=btn('Plan your stay','index.html#inquiry');headerAction.css.m={display:'none'};
C.state.header=[sec('header',[box('header-row',[logo,n('nav','nav',{aria:'Main navigation',items:[{label:'Stays',href:'stays.html'},{label:'The coast',href:'the-coast.html'},{label:'Our story',href:'our-story.html'},{label:'Contact',href:'contact.html'}]},{color:'#fff','font-size':'16px','--nav-hover':'#9fdef0','--nav-panel':c('ink'),'--nav-gap':'24px','justify-self':'end'}),headerAction],{display:'grid','grid-template-columns':'auto 1fr auto','align-items':'center',gap:'24px'},{'grid-template-columns':'1fr auto',gap:'12px'})],{'background-color':c('ink'),padding:'12px 40px'},{padding:'12px 20px'})];
const photoCta=(name:string,title:string,copy:string,asset:string,label:string,href:string)=>{
const photo=image(asset,'100%','100%');photo.css.d={...photo.css.d,position:'absolute',inset:'0'};
const shade=box(name+'-shade',[],{position:'absolute',inset:'0','background-color':'rgba(8,35,48,.62)'});
const panel=box(name+'-stage',[photo,shade,box(name+'-content',[txt(title,'title','h2',{color:'#fff','max-width':'650px'}),txt(copy,'body','p',{color:'#fff','max-width':'48ch','margin-top':'20px'}),box(name+'-action',[btn(label,href)],{'margin-top':'28px'})],{position:'relative','z-index':'1',padding:'88px 40px','max-width':'1280px',margin:'0 auto'},{padding:'56px 20px'})],{position:'relative',overflow:'hidden'});
const section=sec(name,[panel],{padding:'0'},{padding:'0'});section.props.width='full';section.css.t={padding:'0'};return section;};
const footlink=(label:string,href:string)=>{const x=n('footer-link','button',{text:label,link:href,ts:'btn'},{'background-color':'transparent',color:'#fff',padding:'10px 0','border-width':'0','min-height':'44px','justify-content':'flex-start'});x.st={hover:{d:{color:'#9fdef0'},t:{},m:{}}};return x;};
const footgroup=(title:string,links:Node[])=>box('footer-group',[txt(title,'body','h2',{color:'#9fdef0','font-weight':'700'}),box('footer-group-links',links,{display:'flex','flex-direction':'column','align-items':'flex-start','margin-top':'16px'})]);
C.state.footer=[photoCta('closing','Your next slow morning starts here.','Find your place by the water. We’ll help with the rest.','dining','Plan your stay','contact.html#inquiry'),sec('footer',[
box('footer-main',[box('footer-brand',[n('footer-logo','image',{src:'asset:logo',alt:'Cove & Key',link:'index.html'},{width:'240px',height:'52px','object-fit':'contain'}),txt('Coastal homes. Time together. A little room to slow down.','body','p',{color:'#fff','max-width':'30ch','margin-top':'24px'})]),footgroup('Find your stay',homes.map(h=>footlink(h.name,h.slug+'.html'))),footgroup('Make yourself at home',[footlink('Explore the coast','the-coast.html'),footlink('Our story','our-story.html'),footlink('Plan your stay','contact.html#inquiry')])],{display:'grid','grid-template-columns':'1.5fr 1fr 1fr',gap:'64px'},{'grid-template-columns':'1fr',gap:'32px'}),
box('footer-bottom',[txt('Cove & Key · Demo collection','small','p',{color:'#c9dce5'}),txt('Illustrative homes, imagery and reviews. Booking is not connected.','small','p',{color:'#c9dce5'})],{display:'flex','justify-content':'space-between','flex-wrap':'wrap',gap:'12px','margin-top':'56px','padding-top':'24px','border-top':'1px solid #345362'})],{'background-color':c('ink'),padding:'64px 40px 32px'},{padding:'48px 20px 28px'})];
C.state.pages=[home(),collection(),...homes.map((_,i)=>detail(i)),coast(),story(),contact()];for(const p of C.state.pages){if(homes.some(h=>h.slug===p.slug)){const k=p.tree.findIndex(x=>x.id.includes('section-cove-nearby')||x.id.includes('cove-nearby'));if(k>=0)p.tree[k]=photoCta('nearby','The coast is part of the stay.','Leave room for a morning by the water and a long lunch outside.','coast','Explore the coast','the-coast.html');}}C.state.cur=0;normalize(C.state.header);normalize(C.state.footer);C.state.pages.forEach(p=>normalize(p.tree));C.state.meta.components?.forEach(x=>normalize([x.node]));return structuredClone(C.doc());}
