import * as Core from '../../../app/src/core/index.ts';
import type { Doc, Node, Page, Css } from '../../../app/src/core/types.ts';

// Direction studies only. Replace with the selected six-page site after the user checkpoint.
const N = Core.N;
const C = Core.cvar;
let serial = 0;
const named = (node: Node, name: string) => { node.id = `cg-${name}-${++serial}`; return node; };
const box = (name: string, kids: Node[], d: Record<string, string> = {}, m: Record<string, string> = {}) => named(N('box', { layout: 'block' }, { d, t: {}, m }, kids), name);
const heading = (copy: string, level: 'h1' | 'h2' | 'h3' = 'h2', d: Record<string, string> = {}) => named(N('heading', { text: copy, level, ts: level === 'h1' ? 'display' : level === 'h2' ? 'title' : 'subtitle' }, { d: { margin: '0', ...d }, t: {}, m: {} }), 'heading');
const text = (copy: string, style = 'body', d: Record<string, string> = {}) => named(N('text', { html: `<p>${copy}</p>`, ts: style }, { d: { margin: '0', ...d }, t: {}, m: {} }), 'copy');
const img = (asset: string, alt: string, height = '480px', mobile = '310px') => named(N('image', { src: `asset:${asset}`, alt, w: '1536', h: '1024', lazy: 0 }, { d: { width: '100%', height, 'object-fit': 'cover', 'border-radius': '0', display: 'block' }, t: { height: '400px' }, m: { height: mobile } }), asset);
const section = (name: string, kids: Node[], d: Record<string, string> = {}, m: Record<string, string> = {}) => named(N('section', {}, { d: { padding: '56px 32px', ...d }, t: { padding: '40px 24px' }, m: { padding: '32px 20px', ...m } }, kids), name);
const grid = (name: string, kids: Node[], columns = '1fr 1fr', d: Record<string,string> = {}) => box(name, kids, { display: 'grid', 'grid-template-columns': columns, gap: '32px', 'align-items': 'start', ...d }, { 'grid-template-columns': '1fr', gap: '24px' });
const anchor = (node: Node, id: string) => { node.adv.htmlId = id; return node; };
const link = (copy: string, href: string) => named(N('button', { text: copy, link: href, ts: 'btn', variant: 'outline' }, { d: { 'background-color': 'transparent', color: C('ink'), padding: '12px 0', 'border-width': '0', 'border-radius': '0', 'min-height': '44px', 'text-decoration': 'underline', 'text-underline-offset': '5px', 'align-self': 'start' }, t: {}, m: {} }), 'project-link');
const mast = (mode: string) => section('masthead', [box('masthead-content', [heading('Common Ground', 'h2', { 'font-size': mode === 'journal' ? '32px' : '23px', 'letter-spacing': '-.04em', 'white-space': 'nowrap', 'flex-shrink': '0' }), named(N('nav', { collapse: '760', aria: 'Study navigation', items: [{ label: 'Projects', href: '#projects' }, { label: 'Practice', href: '#practice' }] }, { d: { '--nav-gap': '28px', '--nav-panel': C('paper'), '--nav-hover': C('brand'), 'font-size': '16px', color: C('ink') }, t: {}, m: {} }), 'navigation')], { display: 'flex', 'justify-content': mode === 'journal' ? 'center' : 'space-between', 'align-items': 'center', gap: '24px', ...(mode === 'journal' ? { 'flex-direction': 'column' } : {}) }, { 'flex-direction': 'row', 'justify-content': 'space-between', gap: '12px' })], { padding: '24px 32px 20px' }, { padding: '20px' });
const end = () => anchor(section('practice', [text('Common Ground is a fictional architecture practice. Projects and AI-generated imagery are demonstration content, not completed commissions.', 'small', { 'max-width': '76ch', color: C('muted') }), text('<a href="index.html">A · Gallery</a> &nbsp; / &nbsp; <a href="journal.html">B · Journal</a> &nbsp; / &nbsp; <a href="index-study.html">C · Index</a>', 'small', { 'margin-top': '16px' })], { padding: '32px', 'border-top-width': '1px', 'border-top-style': 'solid', 'border-top-color': C('line') }), 'practice');
const projectCaption = (title: string, copy: string) => box('project-caption', [heading(title, 'h2', { 'margin-top': '20px' }), text(copy, 'body', { 'margin-top': '12px', 'max-width': '58ch' })]);

function gallery(): Node[] {
  return [mast('gallery'), section('gallery-opening', [box('opening-copy', [heading('Homes shaped by everyday life.', 'h1'), text('Homes, shared places, and thoughtful ways to work with what is already here.', 'lead', { 'max-width': '46ch', 'margin-top': '20px' }), link('Explore the projects', '#projects')], { 'max-width': '100%', 'margin-bottom': '32px' }), img('courtyard-house', 'Fictional pale-brick courtyard house with a mature olive tree', '540px', '350px')], { padding: '32px 32px 48px' }), anchor(section('gallery-projects', [img('reading-room', 'Fictional workshop converted into a neighborhood reading room', '510px', '300px'), projectCaption('A workshop becomes a reading room.', 'A study in keeping the brick shell, bringing daylight to the table, and giving a familiar building a different public life.')], { 'background-color': C('paper'), padding: '40px 32px 64px' }), 'projects'), end()];
}
function journal(): Node[] {
  return [mast('journal'), section('journal-opening', [heading('Old spaces.\nNew uses.', 'h1', { 'font-family': 'Georgia, serif', 'font-weight': '400', 'text-align': 'center' }), text('Notes on adaptation, material, and the life between buildings.', 'lead', { 'text-align': 'center', 'margin-top': '18px' }), box('journal-media', [img('reading-room', 'Brick, timber and daylight in a fictional reused workshop', '450px', '320px')], { 'margin-top': '32px' }), grid('journal-caption', [text('Reading room / Adaptive reuse', 'small'), text('The old roof sets the rhythm. New joinery gives the room a place to gather, without disguising the building it used to be.')], '1fr 2fr', { 'margin-top': '24px' })], { 'background-color': '#ece4d7' }), anchor(section('journal-material', [grid('material-story', [box('material-image', [img('courtyard-house', 'Brick courtyard with oak-framed windows and olive tree', '430px', '320px')]), box('material-notes', [heading('Brick and shade.', 'h2', { 'font-family': 'Georgia, serif', 'font-weight': '400' }), text('Courtyard house', 'small', { 'margin-top': '16px', color: C('muted') }), text('A sheltered outdoor room connects the kitchen to the garden. Deep openings temper the light; a small tree gives the court its center.', 'body', { 'margin-top': '24px' }), text('The material palette stays close to the structure: pale brick for enclosure, oak where the hand meets the building.', 'body', { 'margin-top': '20px' })])], '1.1fr 1fr')], { padding: '56px 32px' }), 'projects'), end()];
}
function indexStudy(): Node[] {
  return [mast('index'), section('index-opening', [grid('project-directory', [box('directory', [heading('Homes and\nshared places.', 'h1', { 'font-size': 'clamp(34px,3.4vw,48px)' }), text('An architecture practice working across homes and places shared by a neighborhood.', 'body', { 'margin-top': '24px', 'max-width': '34ch' }), box('project-index', [link('Courtyard house', '#courtyard'), link('Workshop reading room', '#projects')], { display: 'flex', 'flex-direction': 'column', 'margin-top': '32px', gap: '4px' })]), box('featured-project', [anchor(img('courtyard-house', 'Street-height view into a fictional brick courtyard house', '540px', '370px'), 'courtyard'), text('Courtyard house · Residential study', 'small', { 'margin-top': '16px' })])], '0.8fr 1.4fr', { gap: '48px' })], { padding: '40px 32px 64px' }), anchor(section('index-project', [grid('project-record', [box('project-facts', [heading('Workshop reading room', 'h2'), text('Adaptive reuse', 'small', { 'margin-top': '16px' }), text('Retain the shell. Open the garden edge. Make one shared table the center of the plan.', 'body', { 'margin-top': '20px', 'max-width': '32ch' })]), img('reading-room', 'Long shared table beneath retained oak trusses in fictional library', '390px', '290px')], '0.8fr 1.4fr', { gap: '48px' })], { 'background-color': '#e9edf0', padding: '40px 32px' }), 'projects'), end()];
}

export function buildTemplateDocument(): Doc {
  Core.seed(); serial = 0;
  const tokens = Core.defaultTokens();
  const palette: Record<string,string> = { bg: '#faf9f6', ink: '#242c27', text: '#242c27', paper: '#faf9f6', brand: '#6c472f', muted: '#586059', line: '#c7cbc5' };
  for (const c of tokens.colors) if (palette[c.id]) c.value = palette[c.id];
  if (!tokens.colors.some(c => c.id === 'paper')) tokens.colors.push({ id: 'paper', name: 'Page surface', value: palette.paper });
  const sizes: Record<string, [string,string]> = { display: ['64px','38px'], title: ['34px','28px'], subtitle: ['24px','22px'], lead: ['21px','19px'], body: ['18px','17px'], small: ['14px','14px'], btn: ['16px','16px'] };
  for (const t of tokens.text) if (sizes[t.id]) { t.css = { d: { 'font-family': 'Arial, sans-serif', 'font-size': sizes[t.id][0], 'font-weight': ['display','title'].includes(t.id) ? '400' : '400', 'line-height': ['display','title'].includes(t.id) ? '1.12' : '1.6', 'letter-spacing': ['display','title'].includes(t.id) ? '-.035em' : '0' }, t: {}, m: { 'font-size': sizes[t.id][1] } } as Css; }
  Core.state.meta = { ...Core.state.meta, name: 'Common Ground — direction studies', maxWidth: '1200px', size: '18px', lang: 'en', font: 'Arial, sans-serif', headFont: 'Arial, sans-serif', css: '', headHtml: '', baseUrl: '', ogImage: 'asset:courtyard-house', favicon: '', blocks: [], components: [], collections: [], selfHostFonts: 0, tokens };
  Core.state.header = []; Core.state.footer = [];
  Core.state.pages = [
    { id: 'page-gallery', name: 'A — Gallery', slug: 'index', title: 'Common Ground — Gallery direction', desc: 'Architecture template direction A. Demonstration only.', tree: gallery() },
    { id: 'page-journal', name: 'B — Journal', slug: 'journal', title: 'Common Ground — Journal direction', desc: 'Architecture template direction B. Demonstration only.', tree: journal() },
    { id: 'page-index', name: 'C — Index', slug: 'index-study', title: 'Common Ground — Index direction', desc: 'Architecture template direction C. Demonstration only.', tree: indexStudy() },
  ] as Page[];
  Core.state.cur = 0;
  return structuredClone(Core.doc());
}
