import * as C from '../../../app/src/core/index.ts';
import type {Doc,Node,Page,ComponentDef} from '../../../app/src/core/types.ts';
type S=Record<string,string>;let serial=0;
const color=C.cvar;
const n=(name:string,type:string,props:Record<string,any>={},d:S={},children:Node[]=[],m:S={},t:S={}):Node=>{const node=C.N(type,props,{d,t,m},children);node.id=`salt-${name}-${++serial}`;return node;};
const text=(copy:string,role='body',level='p',d:S={},m:S={})=>n('text','heading',{text:copy,level,ts:role},{margin:'0',...d},[],m);
const box=(name:string,kids:Node[],d:S={},m:S={})=>n(name,'box',{layout:'block'},d,kids,m);
const section=(name:string,kids:Node[],d:S={},m:S={})=>n(name,'section',{}, {padding:'96px 48px',...d},kids,{padding:'56px 20px',...m},{padding:'56px 32px'});
const row=(name:string,kids:Node[],columns='1fr 1fr',d:S={})=>box(name,kids,{display:'grid','grid-template-columns':columns,gap:'48px',...d},{'grid-template-columns':'1fr',gap:'28px'});
const alts:Record<string,string>={evening:'Illustrative sheltered Mediterranean cove at dusk',cove:'Illustrative Mediterranean cove with clear water and a limestone house',lunch:'Illustrative outdoor lunch table beneath an olive tree',bedroom:'Fictional Dune House bedroom with blue linen and coastal views',terrace:'Fictional Dune House terrace overlooking coastal dunes and the sea',cottage:'Fictional Blue Shutter Cottage living room with pale linen and blue shutters',exterior:'Fictional Blue Shutter Cottage exterior beside a coastal village lane'};
const img=(id:string,height='440px',mobile='300px')=>n(id,'image',{src:`asset:${id}`,alt:alts[id],w:'1536',h:'1024',lazy:0},{display:'block',width:'100%',height,'object-fit':'cover','border-radius':'0'},[],{height:mobile},{height:'380px'});
const link=(copy:string,to:string,plain=false,d:S={})=>n('action','button',{text:copy,link:to,ts:'btn',variant:'outline'},{'background-color':plain?'transparent':color('brand'),color:plain?color('ink'):'#fff','border-radius':'0','border-width':'0',padding:plain?'12px 0':'16px 24px','min-height':'48px',...(plain?{'text-decoration':'underline','text-underline-offset':'6px'}:{}),...d});
const photoLayout=(x:Node)=>{const scene=box('photo-stage',x.children,{...x.css.d,position:'relative'},x.css.m);scene.css.t={...x.css.t};x.children=[scene];x.css={d:{padding:'0'},t:{padding:'0'},m:{padding:'0'}};x.props.width='full';return x;};
const reveal=(x:Node)=>x;
const intro=(title:string,copy:string)=>section('page-opening',[text(title,'display','h1'),text(copy,'lead','p',{'max-width':'48ch','margin-top':'24px'})],{padding:'40px 48px 64px'});
const page=(slug:string,name:string,tree:Node[]):Page=>({id:`salt-page-${slug}`,slug,name,title:`${name} — Salt House`,desc:'A fictional collection of coastal holiday homes. Demonstration property details and AI-generated imagery.',tree});
const anchor=(node:Node,id:string)=>{node.adv.htmlId=id;return node;};
const bind=(node:Node,prop:string,path:string)=>{node.bind={...(node.bind||{}),[prop]:{src:'prop',path}};return node;};
function propertyDefinition():ComponentDef{
 const image=bind(bind(img('cottage','350px','280px'),'src','image'),'alt','alt');image.showIf={bind:{src:'prop',path:'image'},op:'set'};
 image.css.d.transition='filter 0.5s ease';image.st={hover:{d:{filter:'brightness(1.06)'},t:{},m:{}}};
 return {id:'salt-property',name:'Holiday home',node:box('property',[image,box('property-caption',[bind(text('Blue Shutter Cottage','title','h2'),'text','title'),bind(text('4 guests · 2 bedrooms · Village edge','small','p',{'margin-top':'20px',color:color('muted')}),'text','facts'),bind(text('An easy village base, with the sea beyond the shutters.','body','p',{'margin-top':'32px','max-width':'30ch'}),'text','description'),box('nightly-rate',[text('Example nightly rate','small','p',{color:color('muted')}),bind(text('€165 / night','subtitle','p',{'margin-top':'6px'}),'text','price')],{'margin-top':'24px'}),bind(link('Explore this home','blue-shutter-cottage.html',true,{'margin-top':'32px'}),'link','destination')],{padding:'28px 0',display:'flex','flex-direction':'column','justify-content':'center','align-items':'flex-start'},{padding:'24px 0'})],{display:'grid','grid-template-columns':'1fr','background-color':'transparent','min-width':'0'},{'grid-template-columns':'1fr'}),props:[{k:'title',label:'Home name',t:'text',def:'Blue Shutter Cottage'},{k:'price',label:'Example nightly rate',t:'text',def:'€165 / night'},{k:'facts',label:'Home facts',t:'text',def:'4 guests · 2 bedrooms · Village edge'},{k:'description',label:'Home description',t:'text',def:'An easy village base, with the sea beyond the shutters.'},{k:'image',label:'Home photograph',t:'img',def:'asset:cottage'},{k:'alt',label:'Photo description',t:'text',def:alts.cottage},{k:'destination',label:'Home page',t:'link',def:'blue-shutter-cottage.html'}]};
}
const property=(dune=false)=>{const x=box('home-instance',[]);x.use='salt-property';x.vals=dune?{title:'Dune House',price:'€240 / night',facts:'6 guests · 3 bedrooms · Open-air terrace',description:'Space for a larger gathering, with mornings out on the terrace.',image:'asset:terrace',alt:alts.terrace,destination:'dune-house.html'}:{title:'Blue Shutter Cottage',price:'€165 / night',facts:'4 guests · 2 bedrooms · Village edge',description:'An easy village base, with the sea beyond the shutters.',image:'asset:cottage',alt:alts.cottage,destination:'blue-shutter-cottage.html'};return x;};
const homes=()=>box('home-collection',[property(true),property()],{display:'grid','grid-template-columns':'1fr 1fr',gap:'32px'},{'grid-template-columns':'1fr'});
const note=()=>text('Fictional homes and example details. Images are AI-generated; no real rental availability is offered.','small','p',{'margin-top':'32px',color:color('muted'),'max-width':'75ch'});
const editorial=(title:string,copy:string)=>box('reading-group',[text(title,'title','h2'),text(copy,'body','p',{'margin-top':'20px','max-width':'48ch'})]);
function cinema(title:string,copy:string,photo:string,actions:Node[]=[],height='680px'){
 const image=img(photo,height,'600px');image.css.d={...image.css.d,position:'absolute',inset:'0',height:'100%'};image.css.t.height='100%';image.css.m={height:'100%','object-position':'42% center'};
 const shade=box('photo-shade',[],{position:'absolute',inset:'0','background-color':'#101f1c',opacity:'.34'});
 const content=box('photo-message',[reveal(text(title,'display','h1',{color:'#fff','text-align':'center','max-width':'900px',margin:'0 auto'})),text(copy,'lead','p',{color:'#fff','text-align':'center','max-width':'42ch',margin:'24px auto 0'}),box('photo-actions',actions,{display:'flex','justify-content':'center','flex-wrap':'wrap',gap:'16px','margin-top':'32px'})],{position:'relative','z-index':'1','text-align':'center',width:'100%','max-width':'1304px',margin:'0 auto'});
 return photoLayout(section('cinematic-opening',[image,shade,content],{position:'relative','min-height':height,display:'flex','align-items':'center','justify-content':'center',overflow:'hidden'}, {'min-height':'600px'}));
}
function home():Page{
 const openingPhoto=img('terrace','484px','220px');openingPhoto.css.d['grid-row']='span 2';openingPhoto.css.m['grid-row']='auto';
 const smallA=img('cottage','232px','112px'),smallB=img('bedroom','232px','112px');
 smallA.css.t.height='180px';smallB.css.t.height='180px';openingPhoto.css.t.height='380px';
 const images=box('home-photo-preview',[openingPhoto,smallA,smallB],{display:'grid','grid-template-columns':'1.8fr 1fr','grid-template-rows':'1fr 1fr','grid-auto-flow':'dense',gap:'20px'},{'grid-template-columns':'1fr 1fr','grid-template-rows':'auto auto',gap:'12px'});openingPhoto.css.m['grid-column']='1 / -1';

 const choice=(title:string,copy:string,facts:string,dune:boolean)=>box('stay-fit',[
 text(title,'subtitle','h3'),text(copy,'body','p',{'margin-top':'20px','max-width':'34ch'}),text(facts,'small','p',{'margin-top':'24px',color:color('muted')}),link(dune?'Dune House':'Blue Shutter Cottage',dune?'dune-house.html':'blue-shutter-cottage.html',true,{'margin-top':'16px'})
 ],{'border-top-width':'1px','border-top-style':'solid','border-top-color':color('ink'),'padding-top':'24px'});
 const bookingImage=img('evening');bookingImage.css.d={...bookingImage.css.d,position:'absolute',inset:'0',height:'100%'};bookingImage.css.t.height='100%';bookingImage.css.m.height='100%';
 const step=(icon:string,title:string,copy:string)=>box('booking-step',[
 n('booking-'+icon,'icon',{name:icon,label:''},{'--icon-size':'38px','--icon-stroke':'1.5',color:'#fff'}),text(title,'subtitle','h3',{color:'#fff','margin-top':'24px'}),text(copy,'body','p',{color:'#fff','margin-top':'16px','max-width':'32ch'})
 ]);
 const booking=photoLayout(section('arranging-your-holiday',[bookingImage,box('booking-image-shade',[],{position:'absolute',inset:'0','background-color':'#10251f',opacity:'.72'}),box('booking-content',[
 text('Your holiday, in three simple steps.','title','h2',{color:'#fff','max-width':'18ch'}),box('arrival-steps',[step('map-pin','Find your place','Choose the space, setting and sleeping arrangements that suit your people.'),step('calendar','Make a plan','Ask your host about dates, the full price and the details that matter to you.'),step('check-circle','Make it yours','Confirm with the host’s booking provider, then look forward to getting away.')],{display:'grid','grid-template-columns':'repeat(3,minmax(0,1fr))',gap:'56px','margin-top':'48px'},{'grid-template-columns':'1fr',gap:'36px'}),link('Plan your stay','plan-your-stay.html#inquiry',false,{'margin-top':'40px','background-color':color('bg'),color:color('ink')})
 ],{position:'relative','z-index':'1','max-width':'1304px',margin:'0 auto'})],{overflow:'hidden',padding:'88px 48px'}));
 const faq=n('home-booking-questions','accordion',{open:'none',single:1,marker:'plus',items:[{q:'Which home is right for my group?',a:'Dune House has three example bedrooms and sleeps up to six. Blue Shutter Cottage has two bedrooms and sleeps up to four. Check the sleeping arrangements and access information on each home’s page.'},{q:'How do I find prices and available dates?',a:'This is a demonstration collection. The nightly rates shown are illustrative examples, not live quotes. No live availability is supplied. A real collection must connect its booking provider or a working inquiry service before accepting bookings.'},{q:'What should I check before I book?',a:'Confirm the full price, cancellation terms, sleeping arrangements, check-in details and anything your group needs, including parking, steps or pet policies.'}]},{'--ac-q-size':'21px','--ac-a-size':'18px','--ac-q-color':color('bg'),'--ac-a-color':color('bg'),'--ac-mark':color('bg'),'--ac-pad':'28px','--ac-q-weight':'400','--ac-line':'#718078'},[],{'--ac-q-size':'18px','--ac-a-size':'17px'});
 return page('index','Coastal vacation rentals',[
 section('rental-opening',[row('welcome-and-homes',[box('holiday-introduction',[text('Stay by the sea.','display','h1',{'font-size':'60px','max-width':'8ch','font-weight':'500'},{'font-size':'42px','max-width':'12ch'}),text('Coastal holiday homes with room to cook, gather and settle in. Find the space that suits your people.','lead','p',{'max-width':'28ch','margin-top':'24px'}),link('Find your holiday home','#homes',false,{'margin-top':'32px'}),link('Compare the homes','#compare',true,{'margin-top':'12px',display:'block','width':'fit-content'})]),images],'0.85fr 1.5fr',{'align-items':'center',gap:'56px'})],{padding:'40px 48px 64px'}),
 anchor(section('homes-to-stay-in',[text('Two homes. Two ways to stay.','title','h2'),text('Choose outdoor space for the whole group, or a smaller home with the village at your door.','body','p',{'max-width':'60ch','margin-top':'20px'}),box('homes-gallery',[homes()],{'margin-top':'40px'}),note()],{padding:'72px 48px','background-color':color('stays')}),'homes'),
 anchor(section('compare-your-stay',[row('choose-your-pace',[
 box('fit-introduction',[text('A little more space.\nOr a little more village.','title','h2',{'max-width':'16ch'}),text('Find your kind of holiday.','body','p',{'margin-top':'24px',color:color('muted')})]),
 choice('Bring everyone together.','Long lunches on the terrace, room to spread out and an open view of the sea.','Up to 6 guests · 3 bedrooms · 2 bathrooms',true),
 choice('Stay close to village life.','A smaller base for slow mornings, village walks and afternoons behind blue shutters.','Up to 4 guests · 2 bedrooms · 1 bathroom',false)
 ],'1.1fr 1fr 1fr',{gap:'48px','align-items':'start'})],{padding:'88px 48px'}),'compare'),
 section('stay-in-the-place',[row('coastal-setting',[img('cove','520px','300px'),box('place-guide',[text('A coast worth getting to know.','title','h2'),text('A morning swim, lunch in the village or a day that never leaves the terrace. Discover the setting around the homes before choosing your base.','body','p',{'margin-top':'24px','max-width':'36ch'}),link('Explore the coast','coast.html',true,{'margin-top':'24px'}),text('Illustrative Mediterranean setting. Real directions and local recommendations should come from your host.','small','p',{'margin-top':'32px',color:color('muted')})])],'1.2fr 1fr',{'align-items':'center',gap:'64px'})],{padding:'80px 48px'}),
 booking,
 section('answers-before-arrival',[row('planning-answers',[
 box('faq-introduction',[text('Before you\nmake plans.','title','h2',{color:color('bg'),'max-width':'12ch'}),text('A few practical details, so you can start looking forward to your stay.','body','p',{color:color('bg'),'margin-top':'24px','max-width':'28ch'}),link('More planning information','plan-your-stay.html',true,{'margin-top':'24px',color:color('bg')})]),faq
 ],'0.85fr 1.4fr',{gap:'96px','align-items':'start'})],{'background-color':color('ink'),padding:'88px 48px'})
 ]);
}
function collection():Page{return page('homes','The Homes',[
 intro('Make yourself at home.','A terrace for everyone around the table, or a cottage with the village at your door. Find the space that feels like you.'),
 section('all-homes',[homes(),note()],{padding:'0 48px 96px'}),
 section('choose-by-space',[text('Good holidays start with the right fit.','title','h2',{'max-width':'750px'}),text('Both homes are illustrative. Before you book a real stay, confirm sleeping arrangements, access, outdoor space and the full price with the host.','body','p',{'max-width':'65ch','margin-top':'24px'}),link('The practical details','plan-your-stay.html',true,{'margin-top':'20px'})],{'background-color':color('surface')})]);}
function detail(dune:boolean):Page{
 const name=dune?'Dune House':'Blue Shutter Cottage';
 const gallery=n('property-gallery','gallery',{items:(dune?['terrace','bedroom']:['cottage','exterior']).map(x=>({src:`asset:${x}`,alt:alts[x],w:1536,h:1024,caption:x==='exterior'?'Around the cottage':x==='bedroom'?'The bedroom':x==='terrace'?'The terrace':'The living room'})),ratio:'3 / 2',fit:'cover',lightbox:1,lazy:0,captions:1},{'--g-cols':'2','--g-gap':'20px','--g-radius':'0'},[],{'--g-cols':'1'});
 const facts=box('sleeping-and-space',[
 text(dune?'Example rate · €240 / night':'Example rate · €165 / night','subtitle','p',{'margin-bottom':'24px'}),text(dune?'6 guests · 3 bedrooms · 2 bathrooms':'4 guests · 2 bedrooms · 1 bathroom','body'),
 text(dune?'Two doubles and one twin. A broad terrace with space to eat outside.':'One double and one twin. A shaded living room and a village setting.','body','p',{'margin-top':'24px'}),
 link('Inquire about this home','plan-your-stay.html#inquiry',false,{'margin-top':'32px'}),text('Example details. Booking is not connected.','small','p',{'margin-top':'16px',color:color('muted')})],{padding:'32px','background-color':color('surface')});
 return page(dune?'dune-house':'blue-shutter-cottage',name,[
 section('home-heading',[link('All homes','homes.html',true),text(name,'display','h1',{'margin-top':'24px'}),text(dune?'For long lunches and open horizons.':'For village walks and afternoons indoors.','lead','p',{'margin-top':'20px'})],{padding:'32px 48px 48px'}),
 section('home-photographs',[gallery],{padding:'0 48px 48px'}),
 section('home-dossier',[row('story-and-booking',[box('home-story',[text(dune?'The best room is outside.':'Leave the shutters open.','title','h2'),text(dune?'The terrace sets the pace of this example home. Breakfast runs into the morning, lunch stretches into the afternoon, and the sea is always in view. Three bedrooms leave space for a family or a few friends to find their own rhythm.':'Pale linen, blue shutters and light from the coast. This example cottage is a smaller place to return to after a walk through the village, with two bedrooms and a quiet living room for the hours in between.','lead','p',{'margin-top':'24px','max-width':'44ch'})]),facts],'1.3fr 1fr',{'align-items':'start',gap:'64px'}),note()],{padding:'48px 48px 96px'}),
 section('home-practical',[text('A few things to know.','title','h2'),box('practical-lines',[
 box('amenities',[text('Space to settle in','subtitle','h3'),text('Example amenities include an equipped kitchen, dining space, Wi-Fi and a washing machine.','body','p',{'margin-top':'20px'})]),
 box('arrival',[text('Arriving and getting around','subtitle','h3'),text('Confirm parking, steps, transport and access directly with the host. The illustrative setting does not establish real distances.','body','p',{'margin-top':'20px'})]),
 box('booking-terms',[text('Before you book','subtitle','h3'),text('Ask for the total price, cancellation terms, check-in arrangements and any house rules that matter to your group.','body','p',{'margin-top':'20px'})])],{display:'grid','grid-template-columns':'repeat(3,minmax(0,1fr))',gap:'40px','margin-top':'40px'},{'grid-template-columns':'1fr'})],{'background-color':color('surface')}),
 section('another-home',[text('Or a different pace.','title','h2'),box('related-property',[property(!dune)],{'margin-top':'32px'})])]);
}
function coast():Page{return page('coast','The Coast',[
 cinema('Let the day unfold.','A little water, a shaded table and no particular hurry.','cove',[link('Find a place to stay','homes.html')],'580px'),
 section('coast-photo-story',[text('Less planning. More being here.','title','h2',{'max-width':'700px'}),text('A fictional Mediterranean setting, imagined for the simplest kind of holiday.','lead','p',{'margin-top':'24px','max-width':'54ch'}),box('lunch-photograph',[img('lunch','600px','340px')],{'margin-top':'48px'}),text('A table in the shade. Somewhere to stay for a while.','body','p',{'margin-top':'16px'})]),
 section('village-passage',[row('coast-photo-and-guide',[img('exterior','560px','360px'),box('coast-day',[editorial('Start on foot.','Walk through the village before the day warms up. Ask your host for a real local route.'),box('long-lunch',[editorial('Leave time for lunch.','Cook at home or find a shaded table. In a live collection, this is where a host shares their own recommendations.')],{'margin-top':'40px'}),box('water-time',[editorial('Return to the water.','Check local access and swimming conditions. This demonstration does not describe a real beach or safe swimming route.')],{'margin-top':'40px'})])],'1fr 1fr',{'align-items':'center'})],{'background-color':color('surface')})]);}
function plan():Page{
 const faq=n('stay-questions','accordion',{open:'none',single:0,marker:'plus',items:[{q:'How do I check dates and prices?',a:'This demonstration collection is not connected to a booking provider. A real host must supply a working booking link with current availability, full prices and terms.'},{q:'What should I confirm before booking?',a:'Check the total cost, cancellation terms, sleeping arrangements, access, parking and any rules that matter to your group.'},{q:'Can I send an inquiry here?',a:'The form below is disabled until a receiving service is connected. No message is delivered while it is unconfigured.'},{q:'Are these real properties?',a:'No. Salt House is a fictional collection with example details and AI-generated imagery.'}]},{'--ac-q-size':'22px','--ac-a-size':'18px','--ac-q-color':color('ink'),'--ac-a-color':color('text'),'--ac-pad':'24px','--ac-line':color('line')},[],{'--ac-q-size':'19px','--ac-a-size':'17px'});
 const form=n('stay-inquiry','form',{mode:'external',action:'',aria:'Stay inquiry',submit:'Send inquiry',fields:[{label:'Name',name:'name',type:'text',required:1,half:1},{label:'Email',name:'email',type:'email',required:1,half:1},{label:'Home, dates and guests',name:'stay',type:'textarea',required:1}]},{'font-size':'18px','--f-radius':'0','--f-bg':color('bg'),'--f-btn-bg':color('brand'),'--f-btn-fg':'#fff'});
 return page('plan-your-stay','Plan Your Stay',[section('planning-opening',[row('planning-scene',[box('planning-introduction',[text('A good stay starts here.','display','h1'),text('Bring your people. Tell us the dates you have in mind. We’ll leave the rest of the day open.','lead','p',{'margin-top':'24px'}),text('Demonstration collection. No live availability or booking service.','small','p',{'margin-top':'24px',color:color('muted')})]),img('bedroom','440px','280px')],'1fr 1fr',{'align-items':'center'})],{padding:'48px 48px 80px'}),section('planning-questions',[row('questions-and-intro',[editorial('Before you make plans.','Straight answers to the practical questions.'),faq],'1fr 1.6fr')],{'background-color':color('surface')}),anchor(section('inquiry',[row('inquiry-columns',[box('inquiry-context',[text('Tell us what\nyou have in mind.','title','h2'),text('Include your preferred home, approximate dates and group size. Leave payment details and sensitive documents out of your message.','body','p',{'margin-top':'24px'}),text('This demo form is not connected. No inquiry can be sent until a receiving service is configured.','small','p',{'margin-top':'24px',color:color('muted')})]),form],'1fr 1.5fr')]),'inquiry')]);
}
function normalize(nodes:Node[]){for(const x of nodes){for(const bp of ['d','t','m'] as const){const out:S={};for(const [k,v]of Object.entries(x.css[bp])){if(k==='padding'||k==='margin'){const a=String(v).split(/\s+/);['top','right','bottom','left'].forEach((side,i)=>out[k+'-'+side]=[a[0],a[1]||a[0],a[2]||a[0],a[3]||a[1]||a[0]][i]);}else out[k]=String(v);}x.css[bp]=out;}normalize(x.children);}}
export function buildTemplateDocument():Doc{
 C.seed();serial=0;const tokens=C.defaultTokens();tokens.colors=Object.entries({bg:'#f6f3eb',ink:'#293c32',text:'#3c493f',brand:'#a6442d',surface:'#e9e5d9',muted:'#62685e',line:'#c9cebf',stays:'#e3e8df'}).map(([id,value])=>({id,name:({bg:'Chalk',ink:'Olive ink',text:'Body text',brand:'Terracotta',surface:'Sand',muted:'Secondary text',line:'Divider',stays:'Sea sage'} as Record<string,string>)[id],value}));
 const sizes:Record<string,string[]>={display:['72px','58px','42px'],title:['42px','36px','30px'],subtitle:['28px','26px','26px'],lead:['22px','21px','19px'],body:['18px','18px','17px'],small:['16px','16px','14px'],btn:['16px','16px','16px']};
 for(const t of tokens.text)if(sizes[t.id])t.css={d:{'font-family':'inherit','font-size':sizes[t.id][0],'font-weight':'400','line-height':['display','title','subtitle'].includes(t.id)?'1.08':'1.5','letter-spacing':['display','title','subtitle'].includes(t.id)?'-.035em':'0'},t:{'font-size':sizes[t.id][1]},m:{'font-size':sizes[t.id][2]}};
 tokens.text.push({id:'brandmark',name:'Hero brand',tag:'h1',css:{d:{'font-family':'inherit','font-size':'150px','font-weight':'600','line-height':'.9','letter-spacing':'-.07em'},t:{'font-size':'110px'},m:{'font-size':'64px'}}});
 C.state.meta={...C.state.meta,name:'Salt House',lang:'en',maxWidth:'1400px',size:'18px',font:C.stackFor('Outfit','s'),headFont:C.stackFor('Outfit','s'),css:'',headHtml:'',baseUrl:'',ogImage:'asset:terrace',favicon:'',blocks:[],components:[propertyDefinition()],collections:[],selfHostFonts:0,tokens};
 const brand=text('Salt House','subtitle','div',{'font-weight':'600','white-space':'nowrap','flex-shrink':'0'});brand.props.link='index.html';
 C.state.header=[section('header',[box('header-row',[brand,n('navigation','nav',{aria:'Main navigation',items:[{label:'The homes',href:'homes.html'},{label:'The coast',href:'coast.html'},{label:'Plan your stay',href:'plan-your-stay.html'}]},{'font-size':'16px',color:color('ink'),'--nav-panel':color('bg'),'--nav-gap':'32px'})],{display:'flex','justify-content':'space-between','align-items':'center',gap:'24px'})],{padding:'24px 48px'},{padding:'20px'})];
 const footerPhoto=img('evening','360px','320px');footerPhoto.css.d={...footerPhoto.css.d,position:'absolute',inset:'0',height:'100%'};footerPhoto.css.t.height='100%';footerPhoto.css.m.height='100%';
 C.state.footer=[section('closing-photo',[footerPhoto,box('closing-shade',[],{position:'absolute',inset:'0','background-color':'#142d20',opacity:'.25'}),box('closing-invitation',[text('Leave a little room for the coast.','title','h2',{color:'#fff','text-align':'center','max-width':'650px',margin:'0 auto'}),link('Find your home','homes.html',false,{'margin-top':'28px'})],{position:'relative','text-align':'center',width:'100%'})],{position:'relative',overflow:'hidden',padding:'96px 48px'}),section('colophon',[box('footer-navigation',[text('Salt House','subtitle','div',{'font-weight':'500','white-space':'nowrap','flex-shrink':'0'}),box('footer-links',[link('The homes','homes.html',true),link('The coast','coast.html',true),link('Plan your stay','plan-your-stay.html',true)],{display:'flex','flex-wrap':'wrap',gap:'24px'})],{display:'flex',width:'100%','align-items':'center','justify-content':'space-between',gap:'24px'},{'flex-direction':'column','align-items':'flex-start'}),text('A fictional holiday collection. Example property details and AI-generated images.','small','p',{'margin-top':'24px',color:color('muted')})],{padding:'40px 48px'})];
 C.state.pages=[home(),collection(),detail(true),detail(false),coast(),plan()];C.state.footer=C.state.footer.slice(1);C.state.cur=0;for(const p of C.state.pages)for(const section of p.tree)for(const child of section.children)if(child.id.includes('booking-steps'))for(const step of child.children){step.children[0].props.ts='subtitle';step.children[0].props.level='h3';}normalize(C.state.header);normalize(C.state.footer);C.state.pages.forEach(p=>normalize(p.tree));C.state.meta.components?.forEach(c=>normalize([c.node]));return structuredClone(C.doc());
}
