import * as C from '../../../app/src/core/index.ts';
import type {Doc,Node,Page,ComponentDef} from '../../../app/src/core/types.ts';
type S=Record<string,string>; let serial=0; const c=C.cvar;
const n=(name:string,type:string,props:Record<string,any>={},d:S={},children:Node[]=[],m:S={},t:S={}):Node=>{const x=C.N(type,props,{d,t,m},children);x.id=`stillwood-${name}-${++serial}`;if(type==='image'){x.props.w=name==='logo'?820:1536;x.props.h=name==='logo'?180:1024}if(type==='gallery')x.props.items=x.props.items.map((item:any)=>({...item,w:1536,h:1024}));return x};
const text=(copy:string,ts='body',level='p',d:S={})=>n('text','heading',{text:copy,ts,level},{margin:'0',...d});
const box=(name:string,kids:Node[],d:S={},m:S={},t:S={})=>n(name,'box',{layout:d.display==='grid'?'grid':d.display==='flex'?'flex':'block'},d,kids,m,t);
const section=(name:string,kids:Node[],d:S={},m:S={})=>n(name,'section',{}, {padding:'96px 48px',...d},kids,{padding:'56px 22px',...m},{padding:'64px 32px'});
const grid=(name:string,kids:Node[],cols='1fr 1fr',gap='48px')=>box(name,kids,{display:'grid','grid-template-columns':cols,gap,'align-items':'center'},{'grid-template-columns':'1fr',gap:'28px'});
const eyebrow=(copy:string,d:S={})=>text(copy,'small','p',{'text-transform':'uppercase','letter-spacing':'.16em','font-weight':'600',...d});
const button=(label:string,href:string,light=false)=>{const x=n('button','button',{text:label,link:href,ts:'btn'},{padding:'16px 26px','min-height':'50px','border-radius':'0','background-color':light?c('sand'):c('brand'),color:light?c('ink'):'#fff','border-width':'0',transition:'background-color 180ms ease'});x.st={hover:{d:{'background-color':light?'#fff':'#354f3b'},t:{},m:{}}};return x};
const link=(label:string,href:string)=>n('text-link','button',{text:label+' ↗',link:href,ts:'btn'},{padding:'12px 0','min-height':'44px','border-width':'0','background-color':'transparent',color:c('ink'),'justify-content':'flex-start','border-radius':'0','text-decoration':'underline','text-underline-offset':'6px'});
const photo=(id:string,height='440px',mobile='300px')=>n('photo-'+id,'image',{src:`asset:${id}`,alt:`Illustrative ${id==='forest'?'A-frame cabin in conifer woodland':id==='lake'?'cedar cabin beside a lake':id==='meadow'?'cottage in a wildflower meadow':id==='woodland'?'footpath beside a woodland lake':({breakfast:'breakfast on a woodland deck',firepit:'seating around a woodland fire ring',bedroom:'cedar cabin bedroom',picnic:'picnic table in a meadow',trail:'winding fern-lined woodland path',evening:'cabin veranda at dusk',dining:'cabin dining room'} as Record<string,string>)[id]||'pine living room with a wood stove'}; generated demonstration photograph`,lazy:0},{width:'100%',height,'object-fit':'cover',display:'block','border-radius':'0'},[],{height:mobile});
const anchor=(x:Node,id:string)=>{x.adv.htmlId=id;return x};
const title=(small:string,heading:string,copy?:string)=>box('section-intro',[eyebrow(small),text(heading,'title','h2',{'margin-top':'16px'}),...(copy?[text(copy,'body','p',{'margin-top':'20px','max-width':'54ch'})]:[])]);
const homes=[{name:'The A-frame',slug:'the-a-frame',asset:'forest',capacity:2,beds:1,kicker:'For the two of you',description:'A tall window to the trees. A small, warm place to come back to.',feature:'Woodland deck',sleep:'One double bed in an open loft. A staircase leads to the sleeping area.'},{name:'Waterline',slug:'waterline',asset:'lake',capacity:4,beds:2,kicker:'For days by the water',description:'Coffee on the veranda, with the whole lake keeping you company.',feature:'Lakeside veranda',sleep:'One double bedroom and one twin bedroom, both on the ground floor.'},{name:'Meadow House',slug:'meadow-house',asset:'meadow',capacity:6,beds:3,kicker:'For your favourite people',description:'A generous table, a wide porch, and space for everyone to settle in.',feature:'Garden & picnic table',sleep:'Two double bedrooms and one twin bedroom. Ask the host about step-free access.'}];
const bind=(x:Node,key:string,path:string)=>{x.bind={...x.bind,[key]:{src:'prop',path}};return x};
function cabinDefinition():ComponentDef{return{id:'stillwood-cabin',name:'Cabin portrait',node:box('cabin-card',[bind(bind(photo('forest','460px','330px'),'src','image'),'alt','alt'),box('cabin-caption',[bind(eyebrow('For the two of you'),'text','kicker'),bind(text('The A-frame','subtitle','h3',{'margin-top':'12px'}),'text','name'),bind(text('2 guests · 1 bedroom','small','p',{'margin-top':'12px',color:c('muted')}),'text','facts'),bind(text('A quiet place to stay.','body','p',{'margin-top':'16px','max-width':'34ch'}),'text','description'),bind(link('Explore cabin','the-a-frame.html'),'link','destination')],{padding:'26px 0 0'})],{'min-width':'0'}),props:[{k:'image',label:'Cabin image',t:'img',def:'asset:forest'},{k:'alt',label:'Image description',t:'text',def:'Illustrative woodland cabin'},{k:'kicker',label:'Stay style',t:'text',def:'For the two of you'},{k:'name',label:'Cabin name',t:'text',def:'The A-frame'},{k:'facts',label:'Capacity',t:'text',def:'2 guests · 1 bedroom'},{k:'description',label:'Description',t:'text',def:'A quiet place to stay.'},{k:'destination',label:'Cabin page',t:'link',def:'the-a-frame.html'}]}}
const cabin=(i:number)=>{const h=homes[i],x=box('cabin-instance',[]);x.use='stillwood-cabin';x.vals={image:'asset:'+h.asset,alt:`Illustrative ${h.name}`,kicker:h.kicker,name:h.name,facts:`${h.capacity} guests · ${h.beds} bedroom${h.beds>1?'s':''} · ${h.feature}`,description:h.description,destination:h.slug+'.html'};return x};
const carousel=()=>n('cabins','slider',{arrows:1,controlsPosition:'bottom',aria:'Explore the three cabins'},{'--sl-w':'48%','--sl-gap':'40px'},homes.map((_,i)=>cabin(i)),{'--sl-w':'92%','--sl-gap':'20px'});
function form(search=false,home?:string){const fields=[{label:'Arrival',name:'arrival',type:'date',required:1,half:1},{label:'Departure',name:'departure',type:'date',required:1,half:1},{label:'Guests',name:'guests',type:'select',opts:'1 guest,2 guests,3 guests,4 guests,5 guests,6 guests',required:1,half:1},...(!search?[{label:'Your name',name:'name',type:'text',required:1,half:1},{label:'Email',name:'email',type:'email',required:1,half:1},{label:'Cabin',name:'cabin',type:'select',opts:home||'Help me choose,The A-frame,Waterline,Meadow House',half:1},{label:'Anything we should know?',name:'message',type:'textarea',required:0,half:0}]:[])];return n('stay-form','form',{mode:'external',action:'',method:'post',aria:search?'Search cabin stays':`Stay inquiry${home?' for '+home:''}`,submit:search?'Find a cabin':'Send inquiry',fields},{'--f-bg':'#fff','--f-border':c('line'),'--f-text':c('ink'),'--f-label':c('ink'),'--f-btn-bg':c('brand'),'--f-btn-fg':'#fff','--f-radius':'0','--f-gap':'16px','--f-pad':'13px 12px',...(search?{'--f-layout':'grid','--f-columns':'repeat(4,minmax(0,1fr))','--f-button-align':'end','align-items':'end'}:{})},[],search?{'--f-columns':'1fr'}:{},search?{'--f-columns':'repeat(2,minmax(0,1fr))'}:{})}
const questions=[{q:'How do I reserve a cabin?',a:'Choose your cabin and send your preferred dates. This demonstration template does not accept reservations; a host must connect their booking provider before offering live availability.'},{q:'Can I bring a dog?',a:'Pet policies vary by cabin. Ask the host about the cabin you are considering, including any fees and local walking guidance.'},{q:'What should we bring?',a:'Layers, walking shoes, groceries and a good book. Confirm the exact inventory, arrival instructions and weather with your host before travelling.'},{q:'Is there step-free access?',a:'Please discuss your access needs before booking. Cabin descriptions are illustrative and are not an accessibility certification.'}];
const faq=()=>box('faq-rows',questions.map((item,i)=>box('faq-row',[n('faq','accordion',{open:'none',single:1,marker:'plus',items:[item]},{'--ac-q-size':'19px','--ac-a-size':'17px','--ac-pad':'22px','--ac-line':'transparent','--ac-q-color':c('ink'),'--ac-a-color':c('text')})],i?{'border-top':'1px solid '+c('line')}:{})));
const page=(slug:string,name:string,tree:Node[]):Page=>({id:`stillwood-page-${slug}`,slug,name,title:`${name} — Stillwood`,desc:'An illustrative collection of woodland cabins for unhurried days.',tree});
function imageStage(name:string,asset:string,kids:Node[],height='640px'){const p=photo(asset,'100%','100%');p.css.d={...p.css.d,position:'absolute',inset:'0'};const stage=box(name+'-stage',[p,box('shade',[],{position:'absolute',inset:'0','background-image':'linear-gradient(90deg,rgba(12,28,19,.76),rgba(12,28,19,.08))'}),box(name+'-content',kids,{position:'relative','z-index':'1',padding:'88px 48px','max-width':'1344px',margin:'0 auto',width:'100%',display:'flex','flex-direction':'column','justify-content':'center','min-height':height,gap:'24px'},{padding:'64px 22px','min-height':'540px'})],{position:'relative',overflow:'hidden','background-color':c('ink')});const s=section(name,[stage],{padding:'0'},{padding:'0'});s.props.width='full';s.css.t={padding:'0'};return s}
const photoCTA=()=>imageStage('closing','evening',[eyebrow('A few days can feel like a world away.',{color:'#fff'}),text('Leave room\nfor the woods.','display','h2',{color:'#fff','max-width':'650px'}),box('cta-button',[button('Find your cabin','cabins.html',true)])],'440px');
function seasons(){return grid('season-composition',[box('season-copy',[eyebrow('The art of staying in'),text('Rain on the roof.\nNothing on the list.','title','h2',{'margin-top':'18px'}),text('Some days are made for the long way round. Others are made for the chair by the window. There is room for both here.','body','p',{'margin-top':'24px','max-width':'35ch'}),link('Find your kind of day','experiences.html')]),photo('interior','540px','360px')],'0.8fr 1.2fr','80px')}
function itinerary(){return grid('weekend',[box('weekend-title',[eyebrow('A weekend, loosely planned'),text('Arrive. Exhale.\nStay a while.','title','h2',{'margin-top':'20px'}),link('More ways to spend a day','experiences.html')]),box('weekend-timeline',[['01','Friday','Trade the traffic for a timber deck. Unpack, put the kettle on, and let dinner take its time.'],['02','Saturday','Follow a woodland path. Come back hungry. Leave the afternoon open.'],['03','Sunday','One more coffee outside. A final chapter. A slower journey home.']].map(([num,day,copy],i)=>grid('day',[text(num,'title','p',{color:c('muted')}),box('day-copy',[text(day,'subtitle','h3'),text(copy,'body','p',{'margin-top':'10px'})])],'64px 1fr','24px')), {display:'grid',gap:'30px'})],'0.85fr 1.15fr','96px')}
function reviews(){const quotes=['We stopped checking the time. That was the best part.','A book by the window, rain on the roof. Exactly the weekend we needed.','Long breakfasts became our only real plan.','The children found a new favourite corner of the garden every morning.'];return section('guest-stories',[box('review-heading',[eyebrow('Words from a slower weekend'),text('Small moments.\nLong memories.','title','h2',{'margin-top':'16px'}),text('Illustrative guest stories from this demo collection.','small','p',{'margin-top':'16px',color:c('muted')})],{'text-align':'center'}),n('reviews','slider',{arrows:1,controlsPosition:'bottom',aria:'Sample guest stories'},{'--sl-w':'100%','--sl-gap':'28px','max-width':'900px',margin:'32px auto 0'},quotes.map((q,i)=>box('review',[n('quote','quote',{text:q,by:'',source:'',ts:'title'},{margin:'0','font-size':'36px','line-height':'1.3'},[],{'font-size':'27px'}),eyebrow(homes[i%3].name+' · Sample review',{'margin-top':'28px'})],{padding:'24px 40px','text-align':'center'},{padding:'24px 8px'})))],{'background-color':c('sand')})}
function home():Page{return page('index','Woodland cabin stays',[
imageStage('hero','forest',[eyebrow('STILLWOOD / CABINS & QUIET PLACES',{color:'#fff'}),text('A little less doing.\nA little more being.','display','h1',{color:'#fff','max-width':'760px'}),text('Three cabins. All the room you need to slow down.','lead','p',{color:'#fff','max-width':'36ch'}),box('hero-action',[button('Meet the cabins','cabins.html',true)])],'660px'),
anchor(section('search',[form(true)],{padding:'30px 48px','background-color':c('sand')},{padding:'28px 22px'}),'find-a-stay'),
section('welcome',[grid('welcome-layout',[eyebrow('A different pace of place'),text('Out here, the best plans\nleave a little room.','title','h2'),text('For coffee that goes cold. For the path you haven’t tried. For being together without needing to be anywhere else.','body','p')],'0.55fr 1.2fr 0.85fr','48px')]),
section('cabins',[grid('cabins-heading',[title('Find your corner','A cabin for your kind of quiet.'),box('cabins-more',[link('Compare all three','cabins.html')],{'justify-self':'end'})],'1fr auto'),box('cabins-carousel',[carousel()],{'margin-top':'42px'})],{padding:'0 48px 96px'}),
section('indoor-days',[seasons()],{'background-color':c('sand')}),
section('choose-your-stay',[title('It starts with who’s coming','Bring your favourite company.'),box('chooser',homes.map((h,i)=>grid('chooser-row',[text('0'+(i+1),'subtitle','p',{color:c('muted')}),text(h.kicker,'subtitle','h3'),text(`${h.capacity} guests · ${h.feature}`,'body','p'),link(h.name,h.slug+'.html')],'60px 1.1fr 1fr auto','24px')),{'margin-top':'40px',display:'grid',gap:'30px'})]),
section('weekend-notes',[itinerary()],{'background-color':c('brand'),color:'#f6f2e8'}),
section('field-notes',[title('A small field guide','Follow your curiosity.'),box('guide-mosaic',[box('guide-large',[photo('lake','500px','340px'),text('By the water','subtitle','h3',{'margin-top':'20px'}),text('Pack a flask. Find a place to sit. Let the view do the rest.','body','p',{'margin-top':'12px'}),link('Open the field guide','field-guide.html')]),box('guide-small',[photo('meadow','340px','300px'),text('Off the familiar path','subtitle','h3',{'margin-top':'20px'}),text('A meadow walk, a picnic, a detour worth taking.','body','p',{'margin-top':'12px'}),link('Plan a day outside','field-guide.html#outside')],{'padding-top':'110px'},{'padding-top':'0'})],{display:'grid','grid-template-columns':'1.35fr 1fr',gap:'64px','margin-top':'42px'},{'grid-template-columns':'1fr',gap:'32px'})]),
section('comforts',[grid('comforts-layout',[title('Less to pack. More to enjoy.','The good basics,\nthought through.'),box('comfort-list',['A kitchen for proper breakfasts','Bed linen & soft towels','A comfortable corner to read','Outdoor space to make your own','Clear arrival information','A host to ask before you travel'].map((s,i)=>box('comfort',[text('0'+(i+1),'small','p',{color:c('muted')}),text(s,'body','p')],{display:'flex',gap:'20px','padding-bottom':'18px','border-bottom':'1px solid '+c('line')})),{display:'grid','grid-template-columns':'1fr 1fr',gap:'28px'},{'grid-template-columns':'1fr'})],'0.85fr 1.15fr','64px')],{'background-color':c('sand')}),
reviews(),
section('our-way',[box('our-way-center',[eyebrow('The Stillwood way'),text('Good places don’t ask much of you.','title','h2',{'margin-top':'22px'}),text('We believe a stay should make room for ordinary pleasures: a table everyone fits around, a view worth pausing for, and a good night’s sleep.','lead','p',{'margin-top':'24px','max-width':'54ch'}),link('Get to know Stillwood','our-story.html')],{'max-width':'800px',margin:'0 auto','text-align':'center'})]),
section('practical',[grid('practical-layout',[title('Before you set off','A few useful things.','Choose a cabin with confidence. We’ve gathered the questions that help you plan.'),faq()],'0.7fr 1.3fr','96px')],{'background-color':c('sand')})]);}
function cabins(){return page('cabins','Find your cabin',[section('collection-intro',[title('Three places. Three different rhythms.','Where will you settle in?','Compare the cabins by space and setting. All homes and details in this collection are illustrative.' )]),section('collection-list',[text('The cabin collection','subtitle','h2',{'margin-bottom':'28px'}),box('collection',homes.map((_,i)=>cabin(i)),{display:'grid','grid-template-columns':'repeat(3,minmax(0,1fr))',gap:'32px'},{'grid-template-columns':'1fr'})],{padding:'0 48px 96px'}),section('comparison',[title('The practical side','Find the right fit.'),n('compare','table',{head:1,body:'Cabin|Guests|Bedrooms|Setting\nThe A-frame|2|1|Woodland deck\nWaterline|4|2|Lakeside veranda\nMeadow House|6|3|Garden & picnic table',rules:'rows'},{'margin-top':'32px','--tbl-size':'17px','--tbl-pad':'18px','--tbl-line':c('line')}),link('Talk through your plans','contact.html')],{'background-color':c('sand')})])}
function detail(i:number){const h=homes[i];return page(h.slug,h.name,[section('property-title',[eyebrow(h.kicker),text(h.name,'display','h1',{'margin-top':'16px'}),text(h.description,'lead','p',{'margin-top':'20px'}),text(`${h.capacity} guests / ${h.beds} bedroom${h.beds>1?'s':''} / ${h.feature}`,'small','p',{'margin-top':'20px'})],{padding:'48px'}),section('property-gallery',[n('gallery','gallery',{items:[{src:'asset:'+h.asset,alt:`Illustrative ${h.name}`,caption:'The setting'},{src:'asset:interior',alt:'Illustrative cabin interior',caption:'Interior inspiration'}],ratio:'3 / 2',fit:'cover',lightbox:1,lazy:0,captions:1},{'--g-cols':'2','--g-gap':'20px','--g-radius':'0'},[],{'--g-cols':'1'})],{padding:'0 48px 56px'}),section('property-details',[grid('property-layout',[box('property-story',[title('Make yourself at home','A slower day starts here.',h.description+' Come for a change of scene. Stay for the small comforts that make a place feel yours.'),box('rooms',[text('Room to rest','subtitle','h2'),text(h.sleep,'body','p',{'margin-top':'16px'})],{'margin-top':'36px'}),box('features',[text('What’s here','subtitle','h2'),text('Kitchen · Dining table · Linen & towels · Reading space · Outdoor seating','body','p',{'margin-top':'16px'})],{'margin-top':'36px'}),box('arrival',[text('Before you arrive','subtitle','h2'),text('Confirm accessibility, parking, pet rules, check-in times, cancellation terms and the full price with your host. Photographs and facilities shown here are demonstration content.','body','p',{'margin-top':'16px'})],{'margin-top':'36px'})]),anchor(box('booking-widget',[eyebrow('Plan a stay'),text('Make time for '+h.name+'.','subtitle','h2',{'margin-top':'16px'}),box('booking-fields',[form(false,h.name)],{'margin-top':'24px'}),text('Demo booking widget. Connect your PMS to enable live availability and reservations.','small','p',{'margin-top':'20px',color:c('muted')})],{padding:'32px','background-color':c('sand'),position:'sticky',top:'24px'},{padding:'24px',position:'static'}),'booking')],'1.1fr 1fr','72px')]),section('more-cabins',[title('A different corner of Stillwood','Another place to be.'),box('related',[cabin((i+1)%3)],{'max-width':'640px','margin-top':'32px'})],{'background-color':c('sand')})])}
function experiences(){return page('experiences','The slower days',[imageStage('experience-hero','interior',[eyebrow('The slower days',{color:'#fff'}),text('Nothing you have to do.\nPlenty you could.','display','h1',{color:'#fff','max-width':'850px'})],'520px'),section('experience-intro',[title('Find your own rhythm','A day with a little space in it.','Take these as invitations, not an itinerary. Your best day might be the one you never planned.')]),section('experience-weekend',[itinerary()],{'background-color':c('sand')}),section('experience-pair',[grid('pair',[box('outside',[photo('meadow'),text('For the wandering days','subtitle','h2',{'margin-top':'24px'}),text('A path through the trees. Lunch packed in a bag. Ask the host for suitable routes and current conditions.','body','p',{'margin-top':'16px'})]),box('inside',[photo('bedroom'),text('For the staying-in days','subtitle','h2',{'margin-top':'24px'}),text('Make a proper breakfast, choose a book, and claim the chair by the window. Some days need very little else.','body','p',{'margin-top':'16px'})])])]),reviews()])}
function guide(){return page('field-guide','Field guide',[section('guide-intro',[eyebrow('Notes for curious days'),text('Take the long way.','display','h1',{'margin-top':'18px'}),text('An imagined woodland setting, and a few ideas to make it your own. Ask your host for real local recommendations.','lead','p',{'margin-top':'24px','max-width':'56ch'})]),section('guide-water',[photo('lake','580px','320px'),grid('water-notes',[title('01 / By the water','Bring a flask.\nStay for the view.'),text('Find a safe place to sit and watch the light move. Ask about public access and current conditions before heading out. Swimming and boating should only happen where locally permitted.','body','p')],'1fr 1fr')],{padding:'0 48px 96px'}),anchor(section('guide-walking',[grid('walking',[photo('meadow','500px'),title('02 / Outside','Leave room for a detour.','Follow marked routes and the host’s local advice. Bring layers, water and suitable footwear. The best pace is one everyone enjoys.')])],{'background-color':c('sand')}),'outside'),section('guide-food',[title('03 / Back at the cabin','Make dinner part of the day.','Pick up groceries before arrival. Set the table, open the windows, and cook something worth taking your time over.'),link('Find a cabin with room for everyone','cabins.html')])])}
function story(){return page('our-story','Our story',[section('story-intro',[eyebrow('A little about Stillwood'),text('Built around\nthe ordinary good things.','display','h1',{'margin-top':'20px','max-width':'900px'}),text('The warmth of timber. The first coffee outside. A place that gives you permission to do less.','lead','p',{'margin-top':'24px','max-width':'50ch'})]),section('story-image',[photo('forest','580px','360px')],{padding:'0 48px 80px'}),section('story-beliefs',[grid('beliefs',[title('Our point of view','Small collection.\nMore character.'),box('belief-copy',[text('Stillwood is an imagined collection of three woodland homes, created to show how thoughtful hospitality can feel online. Each home has its own character and a clear sense of what a stay could be.','body','p'),text('A good description helps you choose. Honest photographs help you picture the space. Clear practical details help you arrive at ease.','body','p',{'margin-top':'24px'}),link('Explore the collection','cabins.html')])])],{'background-color':c('sand')}),section('story-moment',[seasons()])])}
function contact(){return page('contact','Plan your stay',[section('contact-intro',[eyebrow('The start of something slower'),text('What does your\nweekend look like?','display','h1',{'margin-top':'20px'})]),section('contact-layout',[grid('contact',[box('contact-copy',[photo('interior','430px','320px'),text('A little help choosing?','subtitle','h2',{'margin-top':'28px'}),text('Tell us who’s coming, when you’d like to stay, and what matters most. We’ll start there.','body','p',{'margin-top':'18px'}),text('Demo template: this form is not connected to a recipient.','small','p',{'margin-top':'24px',color:c('muted')})]),box('inquiry',[text('Plan your stay','title','h2'),box('contact-form',[form()],{'margin-top':'24px'})],{padding:'36px','background-color':c('sand')},{padding:'24px'})],'1fr 1fr','72px')],{padding:'0 48px 96px'}),section('contact-questions',[title('Before you send','A few useful answers.'),box('answers',[faq()],{'margin-top':'24px'})],{'background-color':c('sand')})])}
function refineFeedback(doc:Doc){
 const walk=(ns:Node[],f:(x:Node)=>void)=>{for(const x of ns){f(x);walk(x.children,f)}};
 const icon=(name:string)=>n('detail-icon','icon',{name,label:''},{'--icon-size':'28px','--icon-stroke':'1.5',color:c('brand'),padding:'0','background-color':'transparent','align-self':'flex-start'});
 const centered=(heading:string,copy:string)=>box('centered-introduction',[text(heading,'title','h2',{'text-align':'center'}),text(copy,'body','p',{'text-align':'center','max-width':'54ch',margin:'20px auto 0'})],{'max-width':'800px',margin:'0 auto'});
 const home=doc.pages.find(p=>p.slug==='index')!;
 walk(home.tree,x=>{if(x.use==='stillwood-cabin'&&x.vals?.name==='The A-frame'){x.vals.image='asset:bedroom';x.vals.alt='Illustrative cabin bedroom; generated demonstration photograph'}});
 const replace=(part:string,value:Node)=>{const i=home.tree.findIndex(s=>s.id.includes(part));if(i>=0)home.tree[i]=value;};
 replace('welcome',section('welcome',[centered('Out here, the best plans leave a little room.','For coffee that goes cold. For the path you haven’t tried. For being together without needing to be anywhere else.')],{padding:'80px 48px'}));
 replace('choose-your-stay',section('choose-your-stay',[centered('Bring your favourite company.','A hideaway for two, a place by the water, or room for everyone.'),box('photo-choices',homes.map((h,i)=>box('photo-choice',[photo(['breakfast','firepit','picnic'][i],'320px','300px'),box('choice-caption',[icon('users'),text(h.kicker,'subtitle','h3'),text(`${h.capacity} guests · ${h.feature}`,'small','p'),button(h.name,h.slug+'.html')],{display:'flex','flex-direction':'column',gap:'14px',padding:'28px','background-color':c('sand')})],{overflow:'hidden'})),{display:'grid','grid-template-columns':'repeat(3,minmax(0,1fr))',gap:'24px','margin-top':'40px'},{'grid-template-columns':'1fr'})]));
 const weekend=grid('weekend-photo-layout',[photo('trail','620px','340px'),box('weekend-reading',[text('A weekend,\nat your own pace.','title','h2'),box('days',[['Friday','Trade the traffic for a timber deck. Unpack, put the kettle on, and let dinner take its time.'],['Saturday','Follow a woodland path. Come back hungry. Leave the afternoon open.'],['Sunday','One more coffee outside. A final chapter. A slower journey home.']].map(([day,copy])=>box('day',[text(day,'subtitle','h3'),text(copy,'body','p',{'margin-top':'10px'})])),{display:'grid',gap:'28px','margin-top':'32px'}),box('weekend-link',[button('Explore the slower days','experiences.html')],{'margin-top':'32px'})],{'padding-top':'8px'})],'1.1fr 1fr','64px');weekend.css.d['align-items']='start';
 replace('weekend-notes',section('weekend-notes',[weekend],{'background-color':c('sand')}));
 replace('field-notes',imageStage('field-notes','woodland',[text('Follow your curiosity.','title','h2',{color:'#fff','max-width':'620px'}),text('A quiet stretch of water. A path through the trees. Leave the afternoon open.','lead','p',{color:'#fff','max-width':'38ch'}),box('field-action',[button('Open the field guide','field-guide.html',true)])],'620px'));
 replace('comforts',section('comforts',[centered('The good basics, thought through.','Less to pack. More to enjoy.'),box('comforts-details',[
 ['check-circle','A kitchen for proper breakfasts'],['check-circle','Bed linen & soft towels'],['heart','A comfortable corner to read'],['map-pin','Outdoor space to make your own'],['calendar','Clear arrival information'],['chat','A host to ask before you travel']
 ].map(([name,copy])=>box('comfort-detail',[icon(name),text(copy,'body','p')],{display:'flex',gap:'18px','align-items':'center',padding:'20px 0'})),{display:'grid','grid-template-columns':'repeat(3,minmax(0,1fr))',gap:'16px 40px','margin-top':'32px'},{'grid-template-columns':'1fr'})],{'background-color':c('bg')}));
 replace('our-way',imageStage('our-way','dining',[text('Good places don’t\nask much of you.','title','h2',{color:'#fff','max-width':'640px'}),text('A table everyone fits around. A view worth pausing for. A good night’s sleep.','lead','p',{color:'#fff','max-width':'40ch'}),box('our-way-action',[button('Get to know Stillwood','our-story.html',true)])],'540px'));
 walk(home.tree,x=>{if(x.id.includes('practical-layout'))x.css.d['align-items']='start';if(x.id.includes('guest-stories')){x.css.d['background-color']=c('sand');x.css.d['border-top']='1px solid '+c('line');}});
 // Apply the same non-numbered itinerary to the experiences page.
 const exp=doc.pages.find(p=>p.slug==='experiences');if(exp){const s=exp.tree.find(s=>s.id.includes('experience-weekend'));if(s){const copy=structuredClone(weekend);walk([copy],x=>x.id+="-experience");s.children=[copy];}}
 // Linked image nodes have their own alignment defaults. Align the link wrapper as well as the image.
 walk(doc.header,x=>{if(x.type==='image'){Object.assign(x.css.d,{'align-self':'center',display:'block','vertical-align':'middle','object-position':'center'});x.css.m={...x.css.m,'align-self':'center'};}});
 const footlink=(label:string,href:string)=>n('footer-link','button',{text:label,link:href,ts:'btn'},{'background-color':'transparent',color:'#f6f2e8','border-width':'0',padding:'8px 0','min-height':'44px','justify-content':'flex-start'});
 const footlogo=n('footer-logo','image',{src:'asset:logo-light',alt:'Stillwood cabins',link:'index.html',w:820,h:180},{width:'260px',height:'58px',display:'block','object-fit':'contain','align-self':'start'},[],{width:'220px',height:'50px'});
 const foot=section('footer',[box('footer-compact',[footlogo,box('footer-links',[footlink('The cabins','cabins.html'),footlink('The slower days','experiences.html'),footlink('Field guide','field-guide.html'),footlink('Our story','our-story.html'),footlink('Contact','contact.html')],{display:'flex','flex-direction':'row','flex-wrap':'wrap',gap:'8px 24px','justify-content':'flex-end'},{'justify-content':'flex-start',gap:'4px 20px'})],{display:'grid','grid-template-columns':'auto minmax(0,1fr)','align-items':'center',gap:'32px'},{'grid-template-columns':'1fr','align-items':'start',gap:'20px'}),box('footer-bottom',[text('Stillwood · Cabins & quiet places','small','p',{color:'#d4dfce'}),text('Illustrative collection. Booking is not connected.','small','p',{color:'#d4dfce'})],{display:'flex','flex-direction':'row','justify-content':'space-between','flex-wrap':'wrap',gap:'12px','margin-top':'24px','padding-top':'20px','border-top':'1px solid #5d7261'})],{'background-color':c('brand'),padding:'36px 48px 24px'},{padding:'32px 22px 24px'});
 Object.assign(footlogo.css.d,{width:'188px',height:'42px','align-self':'center'});footlogo.css.m={width:'180px',height:'40px','align-self':'flex-start'};
 doc.footer[doc.footer.length-1]=foot;
 // Decorative enumeration is not content; preserve useful words and real capacity numbers.
 walk([...doc.header,...doc.footer,...doc.pages.flatMap(p=>p.tree)],x=>{if(x.type==='heading'&&/^0[1-6]$/.test(String(x.props.text)))x.props.text='';});
}

function normalize(nodes:Node[]){for(const x of nodes){for(const bp of ['d','t','m'] as const){const out:S={};for(const[k,v]of Object.entries(x.css[bp])){if(k==='padding'||k==='margin'){const a=String(v).split(/\s+/);['top','right','bottom','left'].forEach((s,i)=>out[k+'-'+s]=[a[0],a[1]||a[0],a[2]||a[0],a[3]||a[1]||a[0]][i]);}else out[k]=String(v)}x.css[bp]=out;}normalize(x.children)}}
export function buildTemplateDocument():Doc{C.seed();serial=0;const tokens=C.defaultTokens();tokens.colors=Object.entries({bg:'#fbf9f3',ink:'#23382a',text:'#425046',brand:'#233f2e',sand:'#eee9dc',muted:'#60695c',line:'#cecfc2'}).map(([id,value])=>({id,name:id,value}));const sizes:Record<string,string[]>={display:['76px','60px','44px'],title:['48px','40px','34px'],subtitle:['30px','28px','25px'],lead:['21px','20px','19px'],body:['18px','18px','17px'],small:['13px','13px','13px'],btn:['15px','15px','15px']};for(const t of tokens.text)if(sizes[t.id]){const head=['display','title','subtitle'].includes(t.id);t.css={d:{'font-family':head?'Georgia, serif':'inherit','font-size':sizes[t.id][0],'font-weight':head?'400':'400','line-height':head?'1.1':'1.65','letter-spacing':head?'-.035em':'0'},t:{'font-size':sizes[t.id][1]},m:{'font-size':sizes[t.id][2]}}}C.state.meta={...C.state.meta,name:'Stillwood',lang:'en',maxWidth:'1248px',size:'18px',font:'Arial, sans-serif',headFont:'Georgia, serif',css:'',headHtml:'',baseUrl:'',ogImage:'asset:forest',favicon:'asset:symbol',blocks:[],components:[cabinDefinition()],collections:[],selfHostFonts:0,tokens};
const logo=()=>n('logo','image',{src:'asset:logo',alt:'Stillwood cabins',link:'index.html'},{width:'188px',height:'46px','object-fit':'contain'},[],{width:'160px',height:'42px'});
const action=button('Find a cabin','cabins.html');action.css.m={display:'none'};
C.state.header=[section('header',[box('header-row',[logo(),n('navigation','nav',{aria:'Main navigation',items:[{label:'The cabins',href:'cabins.html'},{label:'The slower days',href:'experiences.html'},{label:'Field guide',href:'field-guide.html'},{label:'Our story',href:'our-story.html'}]},{color:c('ink'),'font-size':'15px','--nav-gap':'28px','--nav-hover':'#637b49','--nav-panel':c('bg'),'justify-self':'end'}),action],{display:'grid','grid-template-columns':'auto 1fr auto',gap:'32px','align-items':'center'},{'grid-template-columns':'1fr auto',gap:'14px'})],{padding:'20px 48px','background-color':c('bg')},{padding:'16px 22px'})];
C.state.footer=[photoCTA(),section('footer',[grid('footer-top',[box('footer-brand',[logo(),text('Cabins & quiet places.','lead','p',{'margin-top':'18px'})]),box('footer-explore',[eyebrow('Come on in'),...homes.map(h=>link(h.name,h.slug+'.html'))]),box('footer-plan',[eyebrow('Stay a little longer'),link('The slower days','experiences.html'),link('Field guide','field-guide.html'),link('Plan your stay','contact.html')])],'1.4fr 1fr 1fr','64px'),box('footer-bottom',[text('Stillwood / An illustrative cabin collection','small'),text('Demo homes, imagery and reviews. Reservations are not connected.','small')],{display:'flex','justify-content':'space-between','flex-wrap':'wrap',gap:'16px','margin-top':'56px','padding-top':'24px','border-top':'1px solid '+c('line')})],{padding:'72px 48px 32px'})];
C.state.pages=[home(),cabins(),...homes.map((_,i)=>detail(i)),experiences(),guide(),story(),contact()];// Native node styles, including explicit text alignment and dark-panel contrast.
const walk=(nodes:Node[],fn:(x:Node)=>void)=>{for(const x of nodes){fn(x);walk(x.children,fn)}};
for(const pg of C.state.pages){if(pg.slug==='cabins'){const h=pg.tree[0].children[0].children.find(x=>x.type==='heading'&&x.props.level==='h2');if(h){h.props.level='h1';h.props.ts='display'}}for(const s of pg.tree){if(s.id.includes('weekend-notes'))walk([s],x=>{if(x.type==='button'||x.css.d.color===c('muted'))x.css.d.color='#d8e1cc'});walk([s],x=>{if(x.id.includes('review-heading')||x.id.includes('our-way-center')||/stillwood-review-\d/.test(x.id))walk(x.children,y=>{if(['heading','quote'].includes(y.type))y.css.d['text-align']='center';if(y.type==='heading')y.css.d['margin-left']=y.css.d['margin-right']='auto';});});}
}
walk(C.state.footer,x=>{if(x.id.includes('footer-explore')||x.id.includes('footer-plan'))Object.assign(x.css.d,{display:'flex','flex-direction':'column','align-items':'flex-start',gap:'4px'})});
refineFeedback(C.state as unknown as Doc);C.state.cur=0;normalize(C.state.header);normalize(C.state.footer);C.state.pages.forEach(p=>normalize(p.tree));C.state.meta.components?.forEach(x=>normalize([x.node]));return structuredClone(C.doc());}
