import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from 'esbuild';
import * as Core from '../../app/src/core/index.ts';
import { ANIM_JS } from '../../app/src/core/anim.ts';
import {
  PAGE_PACKAGE_FORMAT_V1, PORTABLE_PACKAGE_LIMITS_V1, SITE_PACKAGE_FORMAT_V1
} from '../../app/src/package/types.ts';
import { blankDoc } from '../../server/src/render.ts';
import { createPagePackage, createSitePackage } from '../../server/src/portable-packages.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const dist = join(here, 'dist');
const editorSource = join(root, 'index.html');
const editor = readFileSync(editorSource, 'utf8');

if (!editor.includes('window.PC_WORDPRESS') || !editor.includes('createWordPressHostAdapter')
  || !editor.includes('documentPath: WP.documentPath') || !editor.includes('HOST.features')
  || !editor.includes('applyHostFeatures')) {
  throw new Error('The Pagecraft build does not expose the WordPress host adapter.');
}

const unwrap = source => source.replace(/^<script>\n?/, '').replace(/<\/script>\s*$/, '').trim();
const runtimeSource = [
  Core.SLIDE_JS,
  Core.CODE_JS,
  Core.TABS_JS,
  Core.NAV_JS,
  Core.FACADE_JS,
  Core.LB_JS,
  `<script>\n${ANIM_JS}\n</script>`
].map(unwrap).join('\n\n');
const runtime = transformSync(runtimeSource, {
  loader: 'js',
  minify: true,
  target: 'es2017',
  legalComments: 'none'
}).code.trim();

mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'editor.html'), editor.replace(
  '<title>Pagecraft Builder</title>',
  '<title>Pagecraft for WordPress</title>'
));
writeFileSync(
  join(dist, 'runtime.js'),
  '/*! GENERATED by @pagecraft/editor. BP Animate licence is bundled by the consuming product. */\n'
    + runtime + '\n'
);
writeFileSync(join(dist, 'contract.json'), JSON.stringify({
  format: 'pagecraft.editor-contract.v1',
  editorVersion: '0.2.11',
  schemaVersion: Core.SCHEMA,
  rendererVersion: `pagecraft-core-${Core.SCHEMA}`,
  hosts: {
    wordpress: 'explicit-feature-contract',
    web: 'explicit-feature-contract'
  },
  packages: {
    site: SITE_PACKAGE_FORMAT_V1,
    page: PAGE_PACKAGE_FORMAT_V1,
    limits: PORTABLE_PACKAGE_LIMITS_V1
  }
}, null, 2) + '\n');

const fixture = blankDoc('WordPress Import Fixture');
fixture.pages[0].id = 'page-import-fixture';
fixture.pages[0].name = 'Imported Landing Page';
fixture.pages[0].slug = 'imported-landing-page';
fixture.pages[0].title = 'Imported Landing Page — Pagecraft';
const header = Core.makeFor('section');
header.id = 'global-header-fixture';
header.props.tag = 'header';
const nav = Core.makeFor('nav');
nav.id = 'global-nav-fixture';
nav.props.items = [{ label: 'Home', href: 'index.html', cls: '', target: '' }];
header.children = [nav];
fixture.header = [header];
const footer = Core.makeFor('section');
footer.id = 'global-footer-fixture';
footer.props.tag = 'footer';
const footerText = Core.makeFor('text');
footerText.id = 'global-footer-text-fixture';
footerText.props.html = '<p>Pagecraft global footer</p>';
footer.children = [footerText];
fixture.footer = [footer];
const section = Core.makeFor('section');
section.id = 'section-import-fixture';
const heading = Core.makeFor('heading');
heading.id = 'heading-import-fixture';
heading.props.text = 'A native Pagecraft page';
const image = Core.makeFor('image');
image.id = 'image-import-fixture';
Object.assign(image.props, {
  src: 'asset:hero-image', alt: 'Pagecraft native media', caption: 'Locally owned in WordPress', w: '1', h: '1'
});
section.css.d['background-image'] = 'url("asset:hero-image")';
const tabs = Core.makeFor('tabs');
tabs.id = 'tabs-import-fixture';
tabs.props.items = [
  { label: 'First', panel: '<p>First panel</p>' },
  { label: 'Second', panel: '<p>Second panel</p>' }
];
section.children = [heading, image, tabs];
fixture.pages[0].tree = [section];
const fixtureAssets = [{
  id: 'hero-image', siteId: 'cloud-project-fixture', name: 'Pagecraft Hero.png', type: 'image/png', w: 1, h: 1,
  bytes: Uint8Array.from(Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2h8sAAAAASUVORK5CYII=',
    'base64'
  ))
}];
const provenance = {
  format: 'pagecraft.provenance.v1', origin: 'pagecraft-cloud',
  sourceId: 'cloud-project-fixture', sourceVersion: 9, exportedBy: 'owner-fixture'
};
const fixturePackage = createPagePackage({
  document: fixture,
  pageId: fixture.pages[0].id,
  assets: fixtureAssets,
  provenance
});
const secondPage = structuredClone(fixture.pages[0]);
secondPage.id = 'page-import-fixture-about';
secondPage.name = 'Imported About Page';
secondPage.slug = 'about';
secondPage.title = 'About — Pagecraft';
fixture.pages.push(secondPage);
const fixtureSitePackage = createSitePackage({ document: fixture, assets: fixtureAssets, provenance });
mkdirSync(join(dist, 'fixtures'), { recursive: true });
writeFileSync(join(dist, 'fixtures', 'page.pagecraft-page.zip'), fixturePackage.bytes);
writeFileSync(join(dist, 'fixtures', 'site.pagecraft-site.zip'), fixtureSitePackage.bytes);

console.log(`@pagecraft/editor artifacts written to ${dist}`);
