/** Disposable Cloud host for template editing QA; binds loopback only, with fixture identity. */
import { serve } from '@hono/node-server';
import { readFile, mkdir, copyFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createApp } from '../server/src/app.ts';
import { MemoryStore } from '../server/src/store.ts';
import { MemoryAuthStore } from '../server/src/auth.ts';
import { MemoryAssetStore } from '../server/src/assets.ts';
import { MemoryOwnedSiteStore } from '../server/src/accounts.ts';
import { FileHostedPublicationStore } from '../server/src/publications.ts';
import { FileSiteTemplateStore } from '../server/src/site-templates.ts';
import { TestHumanChallenge } from '../server/src/turnstile.ts';
import type { AccountAuth } from '../server/src/account-auth.ts';
if (!process.argv.includes('--local-only') || process.env.NODE_ENV === 'production') throw new Error('Explicit --local-only required; never run in production');
const id=process.argv[2],version=process.argv[3];
if (!/^[a-z0-9-]+$/.test(id||'')||!/^\d+\.\d+\.\d+$/.test(version||''))throw new Error('usage: node tools/template-qa-server.ts id version --local-only');
const root=resolve(import.meta.dirname,'..');
const source=resolve(root,'premade-sites',id,version,'draft');
const port=Number(process.env.TEMPLATE_QA_PORT||4890);
if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('Invalid local QA port');
const scratch=resolve(root,port===4890?'.pagecraft-local/template-qa':`.pagecraft-local/template-qa-${port}`);
const catalog=resolve(scratch,'catalog');
const destination=resolve(catalog,id,version);
await mkdir(destination,{recursive:true});
const manifest=JSON.parse(await readFile(resolve(source,'manifest.json'),'utf8'));
await copyFile(resolve(source,'site.pagecraft-site.zip'),resolve(destination,'site.pagecraft-site.zip'));
await writeFile(resolve(catalog,'catalog.json'),JSON.stringify({format:'pagecraft.site-template-catalog.v1',templates:[manifest]}));
const store=new MemoryStore(),auth=new MemoryAuthStore(),assets=new MemoryAssetStore();
const identity={authUserId:'template-local-qa',email:'template-qa@example.invalid',name:'Template QA (local fixture)'};
const accountAuth:AccountAuth={identity:async()=>identity,oauth:async()=>null,signUp:async()=> 'confirmation_required',signIn:async()=>identity,confirm:async()=>identity,forgot:async()=>{},reset:async()=>false,updateEmail:async()=>false,updatePassword:async()=>false,signOut:async()=>{}};
const app=createApp({store,auth,assets,accountAuth,ownedSites:new MemoryOwnedSiteStore(store,auth),challenge:new TestHumanChallenge(),turnstileSiteKey:'local-test-only',editorHost:'localhost',editorOrigin:`http://localhost:${port}`,editorHtml:await readFile(process.env.TEMPLATE_QA_EDITOR_HTML || resolve(root,'index.html'),'utf8'),siteTemplates:new FileSiteTemplateStore(catalog),publications:new FileHostedPublicationStore(resolve(scratch,'publications'))});
serve({fetch:app.fetch,port,hostname:'127.0.0.1'});
console.log(`Template Cloud QA http://localhost:${port} — disposable in-memory data, local fixture identity; not a Supabase authentication test.`);
