/* Turn the vendored bp-animate into a core module.

   Re-runnable on purpose. The alternative was pasting 34 KB into a TypeScript file by hand,
   which makes updating the library an archaeology exercise and hides what we changed from what
   upstream shipped. `vendor/bp-animate/` holds exactly what was downloaded, pinned to a commit
   in PINNED.json; this writes `app/src/core/anim.ts` from it, and the only edit it makes is
   recorded here rather than in the blob.

   That edit is a prefix. Upstream's animation classes are bare — `.fade-in`, `.bounce`,
   `.spin`, `.elastic` — and an exported page is somebody's whole site, where a `.fade-in` of
   their own in Global CSS would collide silently. Everything upstream ships beyond those names
   is already namespaced: `bp-animate`, `bp-is-animating`, the `bp*` keyframes.

   The rename touches both files, not just the stylesheet. The script carries its own map from
   class name to keyframe name and looks the element's classes up in it, so prefixing the CSS
   alone leaves the JavaScript searching for a class that no longer exists — the element gets
   `bp-is-hidden` and simply never animates, with nothing in the console to say why. That is
   how the first version of this shipped, and the check below is what would have caught it: the
   map's keys and the stylesheet's classes have to be the same set.

   Usage: node tools/vendor-anim.mjs
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = join(dirname(fileURLToPath(import.meta.url)), '..');
const v = (f) => join(here, 'vendor', 'bp-animate', f);

const css = readFileSync(v('bp-animate.min.css'), 'utf8');
const js = readFileSync(v('bp-animate.js'), 'utf8');
const pinned = JSON.parse(readFileSync(v('PINNED.json'), 'utf8'));

/* The animation classes, read out of the stylesheet rather than listed here — a hand-kept list
   is how the export drifts from what the CSS can actually do. A rule is one of ours if it is a
   single bare class, optionally qualified by `bp-is-animating`. */
const names = [...new Set(
  [...css.matchAll(/(?:^|[},])\.([a-z][a-z0-9-]*)(?:\.bp-is-animating)?\s*\{/g)]
    .map(m => m[1])
    .filter(n => !n.startsWith('bp-'))
)].sort();
if (names.length < 20) throw new Error(`only found ${names.length} animation classes — the stylesheet shape changed`);

const PFX = 'pc-';

/* The JS map's keys, which have to match the stylesheet's classes — this is the pair that has
   to move together, and comparing them is cheaper than finding out from a page that will not
   animate. `card` and `done-demo` are the demo page's own and appear in neither. */
const mapKeys = [...js.matchAll(/^\s*'([a-z][a-z0-9-]*)':\s*'bp[A-Za-z]+',?$/gm)].map(m => m[1]);
if (!mapKeys.length) throw new Error('could not find the class-to-keyframe map in the script');
const missing = names.filter(n => !mapKeys.includes(n));
if (missing.length) throw new Error(`the stylesheet has classes the script cannot find: ${missing.join(', ')}`);

/* Only in a selector position, so a name appearing inside a value or a comment is left alone. */
let out = css;
for (const n of names) {
  out = out.replaceAll(`.${n}.bp-is-animating`, `.${PFX}${n}.bp-is-animating`);
  out = out.replace(new RegExp(`(^|[},])\\.${n}(?=\\s*\\{)`, 'g'), `$1.${PFX}${n}`);
}
/* Nothing bare may survive, or a page would carry a rule that never matches. */
const leftover = names.filter(n => new RegExp(`(^|[},])\\.${n}(\\.|\\s*\\{)`).test(out));
if (leftover.length) throw new Error(`not prefixed: ${leftover.join(', ')}`);

/* and the same rename in the script's map, so it still recognises the class it is looking at */
let script = js;
for (const n of mapKeys) {
  script = script.replace(new RegExp(`^(\\s*)'${n}':`, 'm'), `$1'${PFX}${n}':`);
}
const unrenamed = mapKeys.filter(n => new RegExp(`^\\s*'${n}':`, 'm').test(script));
if (unrenamed.length) throw new Error(`map keys not prefixed: ${unrenamed.join(', ')}`);

const lit = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

writeFileSync(join(here, 'app', 'src', 'core', 'anim.ts'),
`/* GENERATED by tools/vendor-anim.mjs — do not edit.

   bp-animate, vendored from github.com/braudypedrosa/bp-animate at
   ${pinned.sha} (${pinned.date.slice(0, 10)}). MIT; the licence is in vendor/bp-animate/.

   Vendored rather than linked from a CDN for the same reason the webfonts are: an exported page
   should make no third-party request. The animation classes carry a \`${PFX}\` prefix that
   upstream does not — see the script for why — and \`ANIM_NAMES\` is read out of the stylesheet,
   so the list the inspector offers cannot claim an animation the CSS does not have.
*/
export const ANIM_SHA = ${JSON.stringify(pinned.sha)};
export const ANIM_PFX = ${JSON.stringify(PFX)};
export const ANIM_NAMES: string[] = ${JSON.stringify(names)};
export const ANIM_CSS = ${lit(out)};
export const ANIM_JS = ${lit(script)};
`);

console.log(`anim.ts written — ${names.length} animations, ${Math.round(out.length / 1024)} KB css, ${Math.round(js.length / 1024)} KB js`);
console.log('  ' + names.join(' '));
